### ISSUE TITLE
Not everybody parks

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1214]
On production run I can see failed assertion:
```
05:33:54.448 [ClusterSystem-akka.actor.default-dispatcher-57] ERROR akka.actor.OneForOneStrategy - assertion failed
java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:204)
        at beam.agentsim.agents.PersonAgent$$anonfun$13.applyOrElse(PersonAgent.scala:761)
        at beam.agentsim.agents.PersonAgent$$anonfun$13.applyOrElse(PersonAgent.scala:554)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at beam.agentsim.agents.PersonAgent.akka$actor$LoggingFSM$$super$processEvent(PersonAgent.scala:176)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
        at beam.agentsim.agents.PersonAgent.processEvent(PersonAgent.scala:176)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:638)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at beam.agentsim.agents.PersonAgent.aroundReceive(PersonAgent.scala:176)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
05:33:54.448 [ClusterSystem-akka.actor.default-dispatcher-57] ERROR beam.agentsim.agents.PersonAgent - Got Shutdown. This means actorRef.stop() was called externally, e.g. by supervisor because of an exception.
```

Full log: https://drive.google.com/file/d/1ENSTHfzsasBmLYi0rcOHw1IYG41LcnIB/view?usp=sharing

@michaz , git history shows that you added that assert. What can cause this invalid state, what do you think?

**Comment by michaz** [comment]
Now everybody parks.
