### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in PersonWithCarPlanSpec

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1310]
I can see `java.lang.ArrayIndexOutOfBoundsException` when run `PersonWithCarPlanSpec`:
```
19:35:38.260 [PersonWithCarPlanSpec-akka.actor.default-dispatcher-16] ERROR akka.actor.OneForOneStrategy - 3
java.lang.ArrayIndexOutOfBoundsException: 3
	at scala.collection.mutable.WrappedArray$ofInt.apply$mcII$sp(WrappedArray.scala:173)
	at scala.collection.mutable.WrappedArray$ofInt.apply(WrappedArray.scala:173)
	at scala.collection.mutable.WrappedArray$ofInt.apply(WrappedArray.scala:170)
	at beam.agentsim.agents.vehicles.BeamVehicle$.$anonfun$collectFuelConsumptionData$2(BeamVehicle.scala:219)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at beam.agentsim.agents.vehicles.BeamVehicle$.collectFuelConsumptionData(BeamVehicle.scala:217)
	at beam.agentsim.agents.vehicles.BeamVehicle.useFuel(BeamVehicle.scala:104)
	at beam.agentsim.agents.modalbehaviors.DrivesVehicle$$anonfun$1.applyOrElse(DrivesVehicle.scala:127)
	at beam.agentsim.agents.modalbehaviors.DrivesVehicle$$anonfun$1.applyOrElse(DrivesVehicle.scala:114)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:684)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at beam.agentsim.agents.PersonAgent.akka$actor$LoggingFSM$$super$processEvent(PersonAgent.scala:177)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at beam.agentsim.agents.PersonAgent.processEvent(PersonAgent.scala:177)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at beam.agentsim.agents.PersonAgent.aroundReceive(PersonAgent.scala:177)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[32m- should use another car when the car that is in the plan is taken[0m
19:35:38.265 [PersonWithCarPlanSpec-akka.actor.default-dispatcher-16] ERROR akka.actor.OneForOneStrategy - 3
java.lang.ArrayIndexOutOfBoundsException: 3
	at scala.collection.mutable.WrappedArray$ofInt.apply$mcII$sp(WrappedArray.scala:173)
	at scala.collection.mutable.WrappedArray$ofInt.apply(WrappedArray.scala:173)
	at scala.collection.mutable.WrappedArray$ofInt.apply(WrappedArray.scala:170)
	at beam.agentsim.agents.vehicles.BeamVehicle$.$anonfun$collectFuelConsumptionData$2(BeamVehicle.scala:219)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at beam.agentsim.agents.vehicles.BeamVehicle$.collectFuelConsumptionData(BeamVehicle.scala:217)
	at beam.agentsim.agents.vehicles.BeamVehicle.useFuel(BeamVehicle.scala:104)
	at beam.agentsim.agents.modalbehaviors.DrivesVehicle$$anonfun$1.applyOrElse(DrivesVehicle.scala:127)
	at beam.agentsim.agents.modalbehaviors.DrivesVehicle$$anonfun$1.applyOrElse(DrivesVehicle.scala:114)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:684)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at beam.agentsim.agents.PersonAgent.akka$actor$LoggingFSM$$super$processEvent(PersonAgent.scala:177)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at beam.agentsim.agents.PersonAgent.processEvent(PersonAgent.scala:177)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at beam.agentsim.agents.PersonAgent.aroundReceive(PersonAgent.scala:177)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
Full log: https://beam-ci.tk/job/beam-4ci/4324/consoleFull
Is it because the size of `linkTravelTime` is 5 (https://github.com/LBNL-UCB-STI/beam/blob/master/src/test/scala/beam/agentsim/agents/PersonWithCarPlanSpec.scala#L252, https://github.com/LBNL-UCB-STI/beam/blob/master/src/test/scala/beam/agentsim/agents/PersonWithCarPlanSpec.scala#L291), but the it is overwritten by the container with the size 3 (https://github.com/LBNL-UCB-STI/beam/blob/master/src/test/scala/beam/agentsim/agents/PersonWithCarPlanSpec.scala#L426)

@michaz @colinsheppard , what do you think?

**Comment by michaz** [comment]
> Is it because the size of `linkTravelTime` is 5, but the it is overwritten by the container with the size 3

Not overwritten, but yeah, the travel time array and the link id array in EmbodiedBeamLeg need to have the same size. I don't really want to start with "how to validate case classes". Maybe we should just restructure it two a list of pairs rather than a pair of lists.
