### ISSUE TITLE
Another cases when Vehicle is not parked

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1324]
Run production-sfbay, 411k agents, master branch, commit 3b0be16e597941d9b33947f15f9dc35956bbaae1. There are a few exceptions that Vehicle is not parked:
```
13:26:58.572 [ClusterSystem-akka.actor.default-dispatcher-10] ERROR akka.actor.OneForOneStrategy - My vehicle 105140-3 is not parked.
java.lang.RuntimeException: My vehicle 105140-3 is not parked.
	at beam.agentsim.agents.parking.ChoosesParking$$anonfun$2.$anonfun$applyOrElse$2(ChoosesParking.scala:64)
	at scala.Option.getOrElse(Option.scala:121)
	at beam.agentsim.agents.parking.ChoosesParking$$anonfun$2.applyOrElse(ChoosesParking.scala:64)
	at beam.agentsim.agents.parking.ChoosesParking$$anonfun$2.applyOrElse(ChoosesParking.scala:57)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:684)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at beam.agentsim.agents.PersonAgent.akka$actor$LoggingFSM$$super$processEvent(PersonAgent.scala:177)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at beam.agentsim.agents.PersonAgent.processEvent(PersonAgent.scala:177)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:638)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at beam.agentsim.agents.PersonAgent.aroundReceive(PersonAgent.scala:177)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
Exception with states: https://pastebin.com/VQe27tj1
Full log: https://drive.google.com/open?id=17f_QZn3u7Com1nBLi6WDdyWWR9fOHACl

**Comment by michaz** [comment]
Phew.. I'm not familiar with production-sfbay -- is it very different from sf-light? I'll try sf-light-25k first, to see if I can reproduce it there.

**Comment by REASY** [comment]
It's this branch: https://github.com/LBNL-UCB-STI/beam/tree/production-sfbay. I think the main difference is in the size of the network and how many agents are in the simulation (https://github.com/LBNL-UCB-STI/beam/blob/production-sfbay/production/sfbay/base.conf#L14)

**Comment by michaz** [comment]
Likely fixed in current `develop` with the recent CAV overhaul.

**Comment by JustinPihony** [comment]
Was this verified, though? @REASY @michaz

**Comment by michaz** [comment]
Haven't seen this error in a long time, I fixed a very likely source of non-parked vehicles, but I can't prove there isn't another one.. @REASY Have you seen this lately?
