### ISSUE TITLE
Folder/file name with colon in the path is not allowed in Windows OS

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1350]
Colon (`:`) is reserved char for the filepath in [Windows OS](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#naming-conventions). Colon is used for the [NTFS file streams](https://docs.microsoft.com/en-us/windows/desktop/fileio/file-streams).
When I run production-sfbay on Windows 10, I got
```
00:46:30.421 ERROR o.m.c.c.MatsimRuntimeModifications - Getting uncaught Exception in Thread main
java.nio.file.InvalidPathException: Illegal char <:> at index 72: C:\repos\beam\output\sfbay\base__2019-02-28_00-33-01\numberOfVehicles_CM:Brisbane-Crocker Park BART\summaryStats
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2234)
	at beam.sim.BeamSim.createSummaryStatsGraph(BeamSim.scala:279)
	at beam.sim.BeamSim.$anonfun$notifyIterationEnds$4(BeamSim.scala:176)
	at beam.sim.BeamSim.$anonfun$notifyIterationEnds$4$adapted(BeamSim.scala:176)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:34)
	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:34)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:43)
	at beam.sim.BeamSim.$anonfun$notifyIterationEnds$1(BeamSim.scala:176)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
00:46:30.423 ERROR o.m.c.c.MatsimRuntimeModifications - ERROR --- This is an unexpected shutdown!
```
We should replace all invalid chars for Windows OS also.

**Comment by REASY** [comment]
It seems that that particular path is got because of [NumberOfVehiclesAnalysis.java#L47](https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/java/beam/analysis/summary/NumberOfVehiclesAnalysis.java#L47)
