### ISSUE TITLE
NPE in RealizedModeAnalysis

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1464]
```
21:35:08.692 [scala-execution-context-global-64] ERROR b.a.p.GraphsStatsAgentSimEventsListener - exception: {}
java.lang.NullPointerException: null
        at beam.analysis.plots.RealizedModeAnalysis.writeToReferenceCSV(RealizedModeAnalysis.java:551)
        at beam.analysis.plots.RealizedModeAnalysis.createGraph(RealizedModeAnalysis.java:134)
        at beam.analysis.plots.GraphsStatsAgentSimEventsListener.createGraphs(GraphsStatsAgentSimEventsListener.java:98)
        at beam.sim.BeamSim.$anonfun$notifyIterationEnds$1(BeamSim.scala:160)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/1465
