### ISSUE TITLE
RideHailManager: java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1520]
sf-light-25k run, `production-sfbay` branch, got `java.util.NoSuchElementException: None.get` in [RideHailManager.scala#L871](https://github.com/LBNL-UCB-STI/beam/blob/production-sfbay/src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala#L871)
```
18:12:02.972 [ClusterSystem-akka.actor.default-dispatcher-8] INFO  b.a.scheduler.BeamAgentScheduler - Hour 8.5 completed. 8.2(GB)
18:12:14.652 [ClusterSystem-akka.actor.default-dispatcher-22] INFO  b.a.scheduler.BeamAgentScheduler - Hour 9.0 completed. 4.6(GB)
18:12:16.044 [ClusterSystem-akka.actor.default-dispatcher-51] ERROR akka.actor.OneForOneStrategy - None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at beam.agentsim.agents.ridehail.RideHailManager.cancelReservationDueToFailedModifyPassengerSchedule(RideHailManager.scala:871)
	at beam.agentsim.agents.ridehail.RideHailModifyPassengerScheduleManager.handleInterruptReply(RideHailModifyPassengerScheduleManager.scala:104)
	at beam.agentsim.agents.ridehail.RideHailManager$$anonfun$receive$1.applyOrElse(RideHailManager.scala:721)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at beam.agentsim.agents.ridehail.RideHailManager.aroundReceive(RideHailManager.scala:202)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
18:12:16.049 [ClusterSystem-akka.actor.default-dispatcher-48] ERROR b.a.agents.ridehail.RideHailAgent - Got Shutdown. This means actorRef.stop() was called externally, e.g. by supervisor because of an exception.

```

**Comment by colinsheppard** [comment]
Added fall back in d1484f2d7782d104fbc6e053f337aaf8878a02cf which mistakenly was merged direct to master
