### ISSUE TITLE
debug error on production run - NetworkHelperImpl

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1637]
![image](https://user-images.githubusercontent.com/13569531/55663589-9fb3d180-57e5-11e9-8922-2b7665c78c09.png)

Log (Full log: https://drive.google.com/open?id=1k6jCLEo6XqSmOS83EhrFRJQFRuSifEkd):
```
01:34:24.866 [ClusterSystem-akka.actor.default-dispatcher-58] ERROR beam.utils.NetworkHelperImpl - getLinkUnsafe for -2147483648, when allLinks length is 196344 and MaxLinkId is 196343!
01:34:24.877 [ClusterSystem-akka.actor.default-dispatcher-30] ERROR akka.actor.OneForOneStrategy - Attempt to seek to negative edge number
java.lang.ArrayIndexOutOfBoundsException: Attempt to seek to negative edge number
	at com.conveyal.r5.streets.EdgeStore$Edge.seek(EdgeStore.java:404)
	at com.conveyal.r5.streets.EdgeStore.getCursor(EdgeStore.java:1015)
	at beam.utils.GeoUtils$.getR5EdgeCoord(GeoUtils.scala:9)
	at beam.agentsim.agents.ridehail.RideHailIterationsStatsCollector.calculateActivityEndStats(RideHailIterationsStatsCollector.scala:437)
	at beam.agentsim.agents.ridehail.RideHailIterationsStatsCollector.handleEvent(RideHailIterationsStatsCollector.scala:261)
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:333)
	at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:222)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:136)
	at beam.agentsim.agents.PersonAgent$$anonfun$4.applyOrElse(PersonAgent.scala:349)
	at beam.agentsim.agents.PersonAgent$$anonfun$4.applyOrElse(PersonAgent.scala:332)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at akka.actor.FSM.processEvent(FSM.scala:706)
	at akka.actor.FSM.processEvent$(FSM.scala:703)
	at beam.agentsim.agents.PersonAgent.akka$actor$LoggingFSM$$super$processEvent(PersonAgent.scala:200)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:846)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:828)
	at beam.agentsim.agents.PersonAgent.processEvent(PersonAgent.scala:200)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:700)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:694)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at beam.agentsim.agents.PersonAgent.aroundReceive(PersonAgent.scala:200)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
	at akka.actor.ActorCell.invoke(ActorCell.scala:579)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by REASY** [comment]
I think actual issue is not with NetworkHelper but with [GeoUtils.getNearestR5Edge](https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/sim/common/GeoUtils.scala#L67). In case if there is no split, it will return link id = Int.MinValue.
`GeoUtils.getNearestR5Edge`  used in those places to set link id:
- [ChoosesMode.scala#L1002](https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala#L1002)
- [ChoosesMode.scala#L10029](https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala#L1009)

**Comment by colinsheppard** [comment]
Try increasing the maxRadius parameter first.

**Comment by REASY** [comment]
@colinsheppard suggest to do the following fix? 

On a lazy basis, if we ever fail to find a link, then process all R5 links once and save the 8 links that represent the four corners of the network and the 4 midpoints on the edges of the network bounding box (BB).

We do this by first noting the actual corners and midpoints of the BB, then we sweep once through the network and store the Id of the 8 links that are closest to the BB corners/midpoints.

Store those and then when we fail, just find the stored link on the BB boundary closest to the coord for which a failure occurred.

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/1678
