### ISSUE TITLE
CsvScenarioReader:  java.lang.NumberFormatException: For input string: "1.0"

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1780]
Production run with changes from develop (`./gradlew :run -PappArgs="['--config', 'production/sfbay/smart/smart-baseline.conf']"` fails with:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "1.0"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
        at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
        at beam.utils.scenario.urbansim.CsvScenarioReader$.toHouseholdInfo(CsvScenarioReader.scala:75)
        at beam.utils.scenario.urbansim.CsvScenarioReader$.$anonfun$readHouseholdsFile$1(CsvScenarioReader.scala:59)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
        at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
        at scala.collection.TraversableOnce.to(TraversableOnce.scala:313)
        at scala.collection.TraversableOnce.to$(TraversableOnce.scala:311)
        at scala.collection.AbstractIterator.to(Iterator.scala:1429)
        at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:305)
        at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:305)
        at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1429)
        at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:292)
        at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:286)
        at scala.collection.AbstractIterator.toArray(Iterator.scala:1429)
        at beam.utils.scenario.urbansim.CsvScenarioReader$.$anonfun$readAs$3(CsvScenarioReader.scala:68)
        at beam.utils.FileUtils$.using(FileUtils.scala:80)
        at beam.utils.scenario.urbansim.CsvScenarioReader$.$anonfun$readAs$2(CsvScenarioReader.scala:66)
        at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:7)
        at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:20)
        at beam.utils.scenario.urbansim.CsvScenarioReader$.readAs(CsvScenarioReader.scala:66)
        at beam.utils.scenario.urbansim.CsvScenarioReader$.readHouseholdsFile(CsvScenarioReader.scala:59)
        at beam.utils.scenario.urbansim.UrbanSimScenarioSource.getHousehold(UrbanSimScenarioSource.scala:83)
        at beam.utils.scenario.ScenarioLoader.loadScenario(ScenarioLoader.scala:50)
        at beam.sim.BeamHelper.$anonfun$runBeam$3(BeamHelper.scala:438)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:7)
        at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:20)
        at beam.sim.BeamHelper.runBeam(BeamHelper.scala:438)
        at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:411)
        at beam.sim.RunBeam$.runBeam(RunBeam.scala:3)
        at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:407)
        at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:402)
        at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:3)
        at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:267)
        at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:261)
        at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:3)
        at beam.sim.RunBeam$.main(RunBeam.scala:9)
        at beam.sim.RunBeam.main(RunBeam.scala)

```

**Comment by carloscaldas** [comment]
@REASY the file `smart-baseline.conf` the pointed path does not exist. Where is it?

**Comment by REASY** [comment]
@carloscaldas It's `production-sfbay` branch, https://github.com/LBNL-UCB-STI/beam/blob/production-sfbay/production/sfbay/smart/smart-baseline.conf

**Comment by carloscaldas** [comment]
PR: https://github.com/LBNL-UCB-STI/beam/pull/1766
