### ISSUE TITLE
production-r5-test failed

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1792]
Branch `production-r5-test`, commit 84d30effd0cf27bcaa9982b94fe89b40bf8e08dd, config `production/sfbay/smart/smart-baseline.conf`.
Failed with
```
Exception in thread "main" java.util.NoSuchElementException
	at scala.collection.concurrent.TrieMap.apply(TrieMap.scala:843)
	at beam.agentsim.agents.Population$.$anonfun$getVehiclesFromHousehold$1(Population.scala:160)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at beam.agentsim.agents.Population$.getVehiclesFromHousehold(Population.scala:160)
	at beam.sim.population.PopulationAdjustment$.$anonfun$createAttributesOfIndividual$9(PopulationAdjustment.scala:224)
	at scala.Option.fold(Option.scala:175)
	at beam.sim.population.PopulationAdjustment$.createAttributesOfIndividual(PopulationAdjustment.scala:222)
	at beam.sim.population.PopulationAdjustment.$anonfun$updateAttributes$1(PopulationAdjustment.scala:33)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at beam.sim.population.PopulationAdjustment.updateAttributes(PopulationAdjustment.scala:31)
	at beam.sim.population.PopulationAdjustment.updateAttributes$(PopulationAdjustment.scala:29)
	at beam.sim.population.DefaultPopulationAdjustment.updateAttributes(DefaultPopulationAdjustment.scala:7)
	at beam.sim.population.PopulationAdjustment.update(PopulationAdjustment.scala:48)
	at beam.sim.population.PopulationAdjustment.update$(PopulationAdjustment.scala:45)
	at beam.sim.population.DefaultPopulationAdjustment.update(DefaultPopulationAdjustment.scala:7)
	at beam.sim.BeamHelper.samplePopulation(BeamHelper.scala:660)
	at beam.sim.BeamHelper.samplePopulation$(BeamHelper.scala:578)
	at beam.sim.RunBeam$.samplePopulation(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:462)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:454)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:415)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:406)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:270)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:264)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:5)
	at beam.sim.RunBeam$.main(RunBeam.scala:14)
	at beam.sim.RunBeam.main(RunBeam.scala)
```
Also somehow the log fie does not contain this error, only console log contains

**Comment by colinsheppard** [comment]
Attempt to fix:

46e04475cd4ebf40952902fd18ef26990168efda

**Comment by JustinPihony** [comment]
@colinsheppard Did your attempt fix it? Can this be closed?

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/1798
