### ISSUE TITLE
CaccRoadCapacityGraphs is slow because `XYSeries` is created using default ctor which set autoSort to true

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1800]
Branch https://github.com/LBNL-UCB-STI/beam/tree/production-r5-test_v2, commit: 45c87aeb8f32b747dcaa48bd80d568532c4b612d

It was executing `generateCapacityIncreaseScatterPlotGraph` for more than 3 hours. Stacktrace:
```
"scala-execution-context-global-327" #327 daemon prio=5 os_prio=0 tid=0x00007f5f00002000 nid=0x531e runnable [0x00007f61d70f5000]
   java.lang.Thread.State: RUNNABLE
	at org.jfree.data.xy.XYSeries.add(XYSeries.java:494)
	at org.jfree.data.xy.XYSeries.add(XYSeries.java:475)
	at beam.physsim.jdeqsim.cacc.roadCapacityAdjustmentFunctions.CaccRoadCapacityGraphs.lambda$generateCapacityIncreaseScatterPlotGraph$0(Hao2018CaccRoadCapacityAdjustmentFunction.java:189)
	at beam.physsim.jdeqsim.cacc.roadCapacityAdjustmentFunctions.CaccRoadCapacityGraphs$$Lambda$4193/1552266096.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at beam.physsim.jdeqsim.cacc.roadCapacityAdjustmentFunctions.CaccRoadCapacityGraphs.generateCapacityIncreaseScatterPlotGraph(Hao2018CaccRoadCapacityAdjustmentFunction.java:189)
	at beam.physsim.jdeqsim.cacc.roadCapacityAdjustmentFunctions.Hao2018CaccRoadCapacityAdjustmentFunction.printStats(Hao2018CaccRoadCapacityAdjustmentFunction.java:141)
	at beam.physsim.jdeqsim.cacc.sim.JDEQSimulation.run(JDEQSimulation.java:84)
	at beam.physsim.jdeqsim.AgentSimToPhysSimPlanConverter.setupActorsAndRunPhysSim(AgentSimToPhysSimPlanConverter.java:157)
	at beam.physsim.jdeqsim.AgentSimToPhysSimPlanConverter.startPhysSim(AgentSimToPhysSimPlanConverter.java:405)
	at beam.sim.BeamSim.$anonfun$notifyIterationEnds$8(BeamSim.scala:231)
	at beam.sim.BeamSim$$Lambda$4063/1363009375.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.concurrent.Future$$$Lambda$226/374845463.apply(Unknown Source)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.Future$$Lambda$227/1163871363.apply(Unknown Source)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.Promise$$Lambda$228/1111700510.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
The problem is because of [CaccRoadCapacityAdjustmentFunction.java#L188-L189](https://github.com/LBNL-UCB-STI/beam/blob/production-r5-test_v2/src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java#L188-L189):
```
XYSeries series = new XYSeries("cacc");
caccCapacityIncrease.entries().forEach(e -> series.add(e.getKey(),e.getValue()));
```
It uses constructor [XYSeries.java#L144](https://github.com/jfree/jfreechart/blob/master/src/main/java/org/jfree/data/xy/XYSeries.java#L144) which passes `autoSort=true`.  There are a lot of data points and it tries to sort them on every call `series.add`

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/1798
