### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in beam.analysis.DelayMetricAnalysis.process

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1806]
```
08:51:31.719 [main] ERROR o.m.core.events.EventsManagerImpl - beam.analysis.DelayMetricAnalysis.process(DelayMetricAnalysis.scala:109)
java.lang.ArrayIndexOutOfBoundsException: 182597
	at beam.analysis.DelayMetricAnalysis.process(DelayMetricAnalysis.scala:109)
	at beam.analysis.DelayMetricAnalysis.handleEvent(DelayMetricAnalysis.scala:80)
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:354)
	at org.matsim.core.events.EventsManagerImpl.handle(EventsManagerImpl.java:245)
	at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:231)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:139)
	at beam.sim.LoggingEventsManager.tryToProcessEvent(LoggingEventsManager.scala:120)
	at beam.sim.LoggingEventsManager.handleBlocking(LoggingEventsManager.scala:102)
	at beam.sim.LoggingEventsManager.$anonfun$createDedicatedHandler$1(LoggingEventsManager.scala:94)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Should fix https://github.com/LBNL-UCB-STI/beam/blob/production-r5-test_v2/src/main/scala/beam/analysis/DelayMetricAnalysis.scala#L122, instead of 
```
linkAverageDelay = Array.ofDim[DelayInLength](networkHelper.maxLinkId)
```
it should be 
```linkAverageDelay = Array.ofDim[DelayInLength](networkHelper.maxLinkId + 1)```

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/1798
