### ISSUE TITLE
RideHailFleet initialization from file is broken

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1970]
[RideHailManager.scala#L417](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala#L417) creates `beamScenario.vehicleTypes(Id.create("Car", classOf[BeamVehicleType]))` instead of respecting vehicle type. RideHailManager failed to initialize with exception:
```
akka.actor.ActorInitializationException: akka://ClusterSystem/user/BeamMobsim.iteration/RideHailManager: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:202)
	at akka.actor.ActorCell.create(ActorCell.scala:694)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:545)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:567)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: key not found: Car
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:63)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:63)
	at beam.agentsim.agents.ridehail.RideHailManager.$anonfun$new$4(RideHailManager.scala:419)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at beam.agentsim.agents.ridehail.RideHailManager.<init>(RideHailManager.scala:416)
	at beam.sim.BeamMobsimIteration.$anonfun$rideHailManager$1(BeamMobsim.scala:183)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:88)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:646)
	at akka.actor.ActorCell.create(ActorCell.scala:672)
	... 7 common frames omitted
```

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/1978
