### ISSUE TITLE
Logging class name: Unidentified event type class RefuelEvent

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2011]
Branch: art/production-sfbay-develop-personal-ev-charging, commit: ed2a0b78d5a6447219ad4a625503d68a2e44b002
Full log: https://pastebin.com/Gckje0S0
Error:
```
16:53:53.601 [main] ERROR o.m.c.controler.AbstractController - Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.IllegalStateException: system is in inconsistent state: Logging class name: Unidentified event type class RefuelEvent
	at beam.utils.DebugLib.stopSystemAndReportInconsistency(DebugLib.java:10)
	at beam.agentsim.events.handling.BeamEventsLogger.overrideDefaultLoggerSetup(BeamEventsLogger.java:168)
	at beam.agentsim.events.handling.BeamEventsLogger.<init>(BeamEventsLogger.java:30)
	at beam.agentsim.events.handling.BeamEventsHandling.notifyBeforeMobsim(BeamEventsHandling.java:37)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerBeforeMobsimEvent(ControlerListenerManagerImpl.java:225)
	at org.matsim.core.controler.AbstractController$6.run(AbstractController.java:184)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:181)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:147)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:28)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy26.run(Unknown Source)
	at beam.sim.BeamHelper.run(BeamHelper.scala:679)
	at beam.sim.BeamHelper.run$(BeamHelper.scala:678)
	at beam.sim.RunBeam$.run(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:555)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:533)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:478)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:443)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:307)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:301)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:5)
	at beam.sim.RunBeam$.main(RunBeam.scala:14)
	at beam.sim.RunBeam.main(RunBeam.scala)
```

**Comment by REASY** [comment]
It is because [RefuelEvent](https://github.com/LBNL-UCB-STI/beam/blob/841b33cfcf1e598787a6db0ca28b0271871fb107/src/main/scala/beam/agentsim/events/RefuelEvent.scala) was renamed to [RefuelSessionEvent](https://github.com/LBNL-UCB-STI/beam/blob/5f6e159fccd0c650e44e1fa5a573a34d5ba29324/src/main/scala/beam/agentsim/events/RefuelSessionEvent.scala)

**Comment by REASY** [comment]
For the branch https://github.com/LBNL-UCB-STI/beam/commits/production-sfbay-develop fixed in commit for https://github.com/LBNL-UCB-STI/beam/commit/a214e08e39b65c392c770e730bd9aac4a00b6b32
