### ISSUE TITLE
Vehicle Sharing failing on prod during replanning

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2015]
Branch: production-sfbay-develop-hl-test-vehsharing, commit: 85064b13f8d733914d1ecbed47e66a99cba81ce7
Error:
```
21:31:40.089 [main] INFO  beam.sim.BeamSim - Ending Iteration
21:31:42.817 [main] WARN  ReplanningUtil - person.getSelectedPlan.getPlanElements
21:31:42.817 [main] WARN  ReplanningUtil - [type=Home][coord=[x=535409.4209783552][y=4254443.001749971]][linkId=153178][startTime=undefined][endTime=05:43:04][duration=undefined][facilityId=null]
21:31:42.817 [main] WARN  ReplanningUtil - [mode=][depTime=undefined][travTime=undefined][arrTime=undefined][route=null]
21:31:42.817 [main] WARN  ReplanningUtil - [type=Work][coord=[x=563276.6677138292][y=4236342.4533823775]][linkId=165092][startTime=undefined][endTime=14:54:53][duration=undefined][facilityId=null]
21:31:42.817 [main] WARN  ReplanningUtil - [mode=][depTime=undefined][travTime=undefined][arrTime=undefined][route=null]
21:31:42.817 [main] WARN  ReplanningUtil - [type=Home][coord=[x=535409.4209783552][y=4254443.001749971]][linkId=153178][startTime=undefined][endTime=undefined][duration=undefined][facilityId=null]
21:31:42.817 [main] WARN  ReplanningUtil - experiencedPlan.getPlanElements
21:31:42.817 [main] WARN  ReplanningUtil - [type=Home][coord=null][linkId=153178][startTime=undefined][endTime=05:57:04][duration=undefined][facilityId=null]
21:31:42.817 [main] WARN  ReplanningUtil - [mode=walk_transit][depTime=05:57:04][travTime=01:52:56][arrTime=07:50:00][route= startLinkId=153178 endLinkId=165094 travTime=6776.0 dist=65524.345]
21:31:42.817 [main] WARN  ReplanningUtil - [type=Work][coord=null][linkId=165094][startTime=07:50:00][endTime=14:54:53][duration=undefined][facilityId=null]
21:31:42.817 [main] ERROR o.m.c.c.MatsimRuntimeModifications - Getting uncaught Exception in Thread main
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at beam.replanning.ReplanningUtil$.$anonfun$makeExperiencedMobSimCompatible$3(ReplanningUtil.scala:32)
	at beam.replanning.ReplanningUtil$.$anonfun$makeExperiencedMobSimCompatible$3$adapted(ReplanningUtil.scala:31)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at beam.replanning.ReplanningUtil$.makeExperiencedMobSimCompatible(ReplanningUtil.scala:31)
	at beam.replanning.BeamExpBeta.run(BeamExpBeta.scala:18)
	at org.matsim.core.replanning.GenericStrategyManager.run(GenericStrategyManager.java:213)
	at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:188)
	at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:170)
	at org.matsim.core.controler.corelisteners.PlansReplanningImpl.notifyReplanning(PlansReplanningImpl.java:58)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerReplanningEvent(ControlerListenerManagerImpl.java:206)
	at org.matsim.core.controler.AbstractController$3.run(AbstractController.java:142)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:139)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:28)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy19.run(Unknown Source)
	at beam.sim.BeamHelper.run(BeamHelper.scala:688)
	at beam.sim.BeamHelper.run$(BeamHelper.scala:687)
	at beam.sim.RunBeam$.run(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:555)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:533)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:479)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:453)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:317)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:311)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:5)
	at beam.sim.RunBeam$.main(RunBeam.scala:14)
	at beam.sim.RunBeam.main(RunBeam.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)

```

**Comment by REASY** [comment]
This happens because there are people who were still traveling after 30 hour, that's why `person.getSelectedPlan.getPlanElements` have a different number of elements than `experiencedPlan.getPlanElements`
