### ISSUE TITLE
BeamScoringFunctionFactory: java.lang.IndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2021]
Branch: art/production-sfbay-develop-r5-no-loops, commit: 9baa4a6f013c030e5accd0bccdaa0289601ecd07
Error:
```
07:08:16.247 [main] ERROR o.m.c.c.MatsimRuntimeModifications - Getting uncaught Exception in Thread main
java.lang.IndexOutOfBoundsException: 1
	at scala.collection.mutable.ListBuffer.apply(ListBuffer.scala:132)
	at beam.scoring.BeamScoringFunctionFactory$$anon$1.$anonfun$finish$3(BeamScoringFunctionFactory.scala:94)
	at beam.scoring.BeamScoringFunctionFactory$$anon$1.$anonfun$finish$3$adapted(BeamScoringFunctionFactory.scala:93)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:49)
	at beam.scoring.BeamScoringFunctionFactory$$anon$1.finish(BeamScoringFunctionFactory.scala:93)
	at org.matsim.core.scoring.ScoringFunctionsForPopulation.finishScoringFunctions(ScoringFunctionsForPopulation.java:225)
	at org.matsim.core.scoring.PlansScoringImpl.notifyScoring(PlansScoringImpl.java:58)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerScoringEvent(ControlerListenerManagerImpl.java:184)
	at org.matsim.core.controler.AbstractController$4.run(AbstractController.java:153)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:149)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:28)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy26.run(Unknown Source)
	at beam.sim.BeamHelper.run(BeamHelper.scala:679)
	at beam.sim.BeamHelper.run$(BeamHelper.scala:678)
	at beam.sim.RunBeam$.run(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:555)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:533)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:478)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:443)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:307)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:301)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:5)
	at beam.sim.RunBeam$.main(RunBeam.scala:14)
	at beam.sim.RunBeam.main(RunBeam.scala)
```

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2022
