### ISSUE TITLE
Exception in ChoosesParking

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2039]
Config: [production/sfbay/smart/smart-b-hightech.conf](https://github.com/LBNL-UCB-STI/beam/commits/production-sfbay-develop/production/sfbay/smart/smart-b-hightech.conf)
Branch: production-sfbay-develop
Commit: 8b3996dc935b501ea1c1fe44cd57927d4874dc8e
Full log: https://pastebin.com/wSJt5keb
Error:
```
15:56:38.232 [ClusterSystem-akka.actor.default-dispatcher-312] ERROR akka.actor.OneForOneStrategy - None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:366)
	at scala.None$.get(Option.scala:364)
	at beam.agentsim.agents.parking.ChoosesParking.handleEndCharging(ChoosesParking.scala:398)
	at beam.agentsim.agents.parking.ChoosesParking.handleEndCharging$(ChoosesParking.scala:377)
	at beam.agentsim.agents.PersonAgent.handleEndCharging(PersonAgent.scala:229)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.$anonfun$applyOrElse$4(PersonAgent.scala:350)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.$anonfun$applyOrElse$4$adapted(PersonAgent.scala:348)
	at scala.Option.foreach(Option.scala:274)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.$anonfun$applyOrElse$3(PersonAgent.scala:348)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.$anonfun$applyOrElse$3$adapted(PersonAgent.scala:345)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.applyOrElse(PersonAgent.scala:345)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.applyOrElse(PersonAgent.scala:337)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at akka.actor.FSM.processEvent(FSM.scala:706)
	at akka.actor.FSM.processEvent$(FSM.scala:703)
	at beam.agentsim.agents.PersonAgent.akka$actor$LoggingFSM$$super$processEvent(PersonAgent.scala:229)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:846)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:828)
	at beam.agentsim.agents.PersonAgent.processEvent(PersonAgent.scala:229)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:700)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:694)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at beam.agentsim.agents.PersonAgent.aroundReceive(PersonAgent.scala:229)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
	at akka.actor.ActorCell.invoke(ActorCell.scala:579)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by colinsheppard** [comment]
so far I cannot reproduce
