### ISSUE TITLE
bug: if PopulationAdjustment applied, changes from AvailableModes don't make it into PersonAgents

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2107]
I’m trying to use PopulationAdjustment and it doesn’t seem like the changes I make to AvailableModes in there end up in the final PersonAgents.

**Comment by carloscaldas** [comment]
Possible bug. Steps to reproduce:
1. In `beam.conf` replace the line 
`beam.agentsim.populationAdjustment="DEFAULT_ADJUSTMENT"`
with 
`beam.agentsim.populationAdjustment="PERCENTAGE_ADJUSTMENT"`

2. Run beamville

Exceptoins:
```
00:38:14.112 INFO  b.a.RideHailUtilizationCollector - Created RideHailUtilizationCollector with hashcode: 244788961
Exception in thread "main" java.lang.NullPointerException
	at beam.utils.plan.sampling.AvailableModeUtils$.availableModesForPerson(AvailableModeUtils.scala:58)
	at beam.sim.population.PopulationAdjustment.removeMode(PopulationAdjustment.scala:137)
	at beam.sim.population.PopulationAdjustment.removeMode$(PopulationAdjustment.scala:135)
	at beam.sim.population.PercentagePopulationAdjustment.removeMode(PercentagePopulationAdjustment.scala:7)
	at beam.sim.population.PopulationAdjustment.$anonfun$removeModeAll$1(PopulationAdjustment.scala:150)
	at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:559)
	at beam.sim.population.PopulationAdjustment.removeModeAll(PopulationAdjustment.scala:149)
	at beam.sim.population.PopulationAdjustment.removeModeAll$(PopulationAdjustment.scala:148)
	at beam.sim.population.PercentagePopulationAdjustment.removeModeAll(PercentagePopulationAdjustment.scala:7)
	at beam.sim.population.PercentagePopulationAdjustment.updatePopulation(PercentagePopulationAdjustment.scala:15)
	at beam.sim.population.PopulationAdjustment.update(PopulationAdjustment.scala:55)
	at beam.sim.population.PopulationAdjustment.update$(PopulationAdjustment.scala:54)
	at beam.sim.population.PercentagePopulationAdjustment.update(PercentagePopulationAdjustment.scala:7)
	at beam.sim.BeamHelper.samplePopulation(BeamHelper.scala:780)
	at beam.sim.BeamHelper.samplePopulation$(BeamHelper.scala:700)
	at beam.sim.RunBeam$.samplePopulation(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:549)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:543)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:488)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:453)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:317)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:311)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:5)
	at beam.sim.RunBeam$.main(RunBeam.scala:14)
	at beam.sim.RunBeam.main(RunBeam.scala)
```

**Comment by carloscaldas** [comment]
closed by https://github.com/LBNL-UCB-STI/beam/pull/2774
