### ISSUE TITLE
Slowdown on b-ht scenarios over time for jdeqsim

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2188]
Stacktrace showed:
```
"scala-execution-context-global-13784" #13784 daemon prio=5 os_prio=0 tid=0x00007f0350001000 nid=0x9425 runnable [0x00007f0c038f7000]
   java.lang.Thread.State: RUNNABLE
    at java.lang.Runtime.freeMemory(Native Method)
    at beam.utils.DebugLib.gcAndGetMemoryLogMessage(DebugLib.java:24)
    at beam.physsim.jdeqsim.JDEQSimMemoryFootprint.handleEvent(JDEQSimMemoryFootprint.java:24)
    at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:354)
    at org.matsim.core.events.EventsManagerImpl.handle(EventsManagerImpl.java:245)
    at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:231)
    - locked <0x00007f1c5157bae8> (a beam.physsim.jdeqsim.JDEQSimMemoryFootprint)
    at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:139)
    at org.matsim.core.mobsim.jdeqsim.LeaveRoadMessage.processEvent(LeaveRoadMessage.java:51)
    at org.matsim.core.mobsim.jdeqsim.Scheduler.startSimulation(Scheduler.java:62)
    at org.matsim.core.mobsim.jdeqsim.JDEQSimulation.run(JDEQSimulation.java:74)
    at beam.physsim.jdeqsim.cacc.sim.JDEQSimulation.run(JDEQSimulation.java:83)
    at beam.physsim.jdeqsim.AgentSimToPhysSimPlanConverter.setupActorsAndRunPhysSim(AgentSimToPhysSimPlanConverter.java:173)
    at beam.physsim.jdeqsim.AgentSimToPhysSimPlanConverter.startPhysSim(AgentSimToPhysSimPlanConverter.java:444)
    at beam.sim.BeamSim.$anonfun$notifyIterationEnds$8(BeamSim.scala:268)
    at beam.sim.BeamSim$$Lambda$4764/962444034.apply$mcV$sp(Unknown Source)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
    at scala.concurrent.Future$$$Lambda$174/1214753695.apply(Unknown Source)
    at scala.util.Success.$anonfun$map$1(Try.scala:255)
    at scala.util.Success.map(Try.scala:213)
    at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
    at scala.concurrent.Future$$Lambda$175/1508130444.apply(Unknown Source)
    at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
    at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
    at scala.concurrent.impl.Promise$$Lambda$176/956061012.apply(Unknown Source)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
`beam.debug.debugEnabled = true` is set to `true`, so it means every hour JDEQSim will force GC.
It spends a lot of time in GC: https://gceasy.io/my-gc-report.jsp?p=c2hhcmVkLzIwMTkvMDkvMjMvLS1nY18wOS0yMC0yMDE5XzIxLTEyLTQzLmxvZy50eHQtLTE2LTE0LTE3&channel=WEB

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2189
