### ISSUE TITLE
sf-light-25k fails when ride hail is utilized heavily

### ISSUE THREAD

**Issue by estandiaa-marain** [LBNL-UCB-STI/beam#2206]
Hello team,
sf-light-25k fails when ride hail is utilized heavily. This can be achieved by setting
```
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.ride_hail_intercept = 100.0
```

Iteration 0 completes but then the simulation fails at around hour 8 of iteration 1. I have observed 2 failure modes for this when running the same config. I am attaching the config file and the 2 log files.

One failure mode starts with
```
07:02:45.665 [ClusterSystem-akka.actor.default-dispatcher-1036] ERROR b.a.agents.ridehail.RideHailManager - Going to stop child of RHM because of key not found: BeamLeg(CAR @ 29475,dur:203,path: 37059 .. 6352)
java.util.NoSuchElementException: key not found: BeamLeg(CAR @ 29475,dur:203,path: 37059 .. 6352)
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.immutable.TreeMap.default(TreeMap.scala:50)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.immutable.TreeMap.apply(TreeMap.scala:50)
	at beam.agentsim.agents.modalbehaviors.DrivesVehicle$$anonfun$3.applyOrElse(DrivesVehicle.scala:607)
	at beam.agentsim.agents.modalbehaviors.DrivesVehicle$$anonfun$3.applyOrElse(DrivesVehicle.scala:583)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at akka.actor.FSM.processEvent(FSM.scala:706)
	at akka.actor.FSM.processEvent$(FSM.scala:703)
	at beam.agentsim.agents.ridehail.RideHailAgent.akka$actor$LoggingFSM$$super$processEvent(RideHailAgent.scala:160)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:846)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:828)
	at beam.agentsim.agents.ridehail.RideHailAgent.processEvent(RideHailAgent.scala:160)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:700)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:694)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at beam.agentsim.agents.ridehail.RideHailAgent.aroundReceive(RideHailAgent.scala:160)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
	at akka.actor.ActorCell.invoke(ActorCell.scala:579)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The other with 
```
20:22:40.863 [ClusterSystem-akka.actor.default-dispatcher-915] ERROR akka.actor.OneForOneStrategy - None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:366)
	at scala.None$.get(Option.scala:364)
	at beam.agentsim.agents.ridehail.RideHailModifyPassengerScheduleManager.sendNewPassengerScheduleToVehicle(RideHailModifyPassengerScheduleManager.scala:191)
	at beam.agentsim.agents.ridehail.RideHailManager.handleReservation(RideHailManager.scala:1333)
	at beam.agentsim.agents.ridehail.RideHailManager.$anonfun$findAllocationsAndProcess$1(RideHailManager.scala:1520)
	at beam.agentsim.agents.ridehail.RideHailManager.$anonfun$findAllocationsAndProcess$1$adapted(RideHailManager.scala:1509)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at beam.agentsim.agents.ridehail.RideHailManager.beam$agentsim$agents$ridehail$RideHailManager$$findAllocationsAndProcess(RideHailManager.scala:1509)
	at beam.agentsim.agents.ridehail.RideHailManager$$anonfun$receive$1.applyOrElse(RideHailManager.scala:747)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at beam.agentsim.agents.ridehail.RideHailManager.aroundReceive(RideHailManager.scala:202)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
	at akka.actor.ActorCell.invoke(ActorCell.scala:579)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

In both cases, there are a bunch of errors like this before the simulation fails:
```
20:22:40.727 [ClusterSystem-akka.actor.default-dispatcher-1010] ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-020900-2015001119273-1-2336318.
```

I tried cleaning the build and deleting the temporary files in the r5 directory but the problem persists.

Thanks in advance.

[beam.conf.txt](https://github.com/LBNL-UCB-STI/beam/files/3700398/beam.conf.txt)
[beamLog_1.out.txt](https://github.com/LBNL-UCB-STI/beam/files/3700399/beamLog_1.out.txt)
[beamLog_2.out.txt](https://github.com/LBNL-UCB-STI/beam/files/3700400/beamLog_2.out.txt)

**Comment by colinsheppard** [comment]
@estandiaa-marain thanks for alerting us to this. I have some time in the next day to look into it.

**Comment by wrashid** [comment]
tried to reproduce - gets stuck with following error in iteration 1 at hour 13:
```
08:25:16.638 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-017802-2012000371869-1-5643449
08:26:01.312 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-020100-2014001201568-0-939100
08:26:01.312 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-017601-2014000387477-3-1064393
08:26:01.312 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-023003-2016001481758-0-948927
08:26:01.312 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-016500-2013000119948-0-4756808
08:26:01.312 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-021700-2014000095176-0-7569061
08:26:01.328 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-017601-2014000443569-1-3863052
08:26:01.328 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-010900-2012001370971-0-1311480
08:26:02.343 ERROR b.a.agents.ridehail.RideHailManager - RideHailModifyPassengerScheduleManager- interruptId not found: interruptId 645271,interruptedPassengerSchedule NA, vehicle rideHailVehicle-021700-2014000095176-0-7569061, tick 47412
08:26:02.343 WARN  b.a.agents.ridehail.RideHailManager - Have not expected to see 'None'
```

full log: 
[beamLog.out.txt](https://github.com/LBNL-UCB-STI/beam/files/3717541/beamLog.out.txt)

**Comment by wrashid** [comment]
just tested it with beam.agentsim.agents.rideHail.allocationManager.name="POOLING_ALONSO_MORA" => that run not have any issues
