### ISSUE TITLE
IndexOutOfBoundsException on master (sf-light 2.5k scenario)

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#227]
- reproduce with sf-light 2.5k run

java.lang.IndexOutOfBoundsException: 0
	at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:123) ~[scala-library-2.12.4.jar:?]
	at scala.collection.immutable.Vector.apply(Vector.scala:114) ~[scala-library-2.12.4.jar:?]
	at beam.agentsim.agents.vehicles.VehicleStack.outermostVehicle(BeamVehicle.scala:288) ~[classes/:?]
	at beam.agentsim.agents.PersonAgent$$anonfun$8.applyOrElse(PersonAgent.scala:234) ~[classes/:?]
	at beam.agentsim.agents.PersonAgent$$anonfun$8.applyOrElse(PersonAgent.scala:199) ~[classes/:?]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34) ~[scala-library-2.12.4.jar:?]
	at beam.agentsim.agents.BeamAgent.$anonfun$handleEvent$1(BeamAgent.scala:92) ~[classes/:?]
	at beam.agentsim.agents.BeamAgent.$anonfun$handleEvent$1$adapted(BeamAgent.scala:90) ~[classes/:?]
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:78) ~[scala-library-2.12.4.jar:?]

**Comment by colinsheppard** [comment]
After patch above, I got through 3 full iterations without any errors. So I think it's fixed, will close this after travis completes.
