### ISSUE TITLE
Prod run fails with error "java.lang.IllegalStateException: system is in inconsistent state: Logging class name: Unidentified event type class ParkEvent"

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2334]
Run details:
```
Config: production/sfbay/smart/smart-baseline.conf
Run Name** art/smart-baseline-network-relax-exp4.0_reasyuATgmail_com**
Instance ID i-051b59a07b5026e96
Instance type **m5d.24xlarge**
Host name **ec2-18-217-75-35.us-east-2.compute.amazonaws.com**
Web browser ** http://ec2-18-217-75-35.us-east-2.compute.amazonaws.com:8000 **
Region us-east-2
Batch 002ac1f1
Branch **art/#2270-network-relax-prod**
Commit 27d99f72b248462c7bcc04646d73594064fc6fa8
S3 output url  https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/sfbay/sfbay-smart-base-relax-exp_4.0__2020-01-18_11-43-46_azj
Shutdown in 15 minutes
```

```
Exception in thread "main" java.lang.IllegalStateException: system is in inconsistent state: Logging class name: Unidentified event type class ParkEvent
	at beam.utils.DebugLib.stopSystemAndReportInconsistency(DebugLib.java:10)
	at beam.agentsim.events.handling.BeamEventsLogger.overrideDefaultLoggerSetup(BeamEventsLogger.java:176)
	at beam.agentsim.events.handling.BeamEventsLogger.<init>(BeamEventsLogger.java:29)
	at beam.agentsim.events.handling.BeamEventsLogger.<init>(BeamEventsLogger.java:33)
	at beam.agentsim.events.handling.BeamEventsHandling.notifyBeforeMobsim(BeamEventsHandling.java:37)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerBeforeMobsimEvent(ControlerListenerManagerImpl.java:225)
	at org.matsim.core.controler.AbstractController$6.run(AbstractController.java:184)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:181)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:147)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:28)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy28.run(Unknown Source)
	at beam.sim.BeamHelper.run(BeamHelper.scala:709)
	at beam.sim.BeamHelper.run$(BeamHelper.scala:708)
	at beam.sim.RunBeam$.run(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:583)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:561)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:473)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:461)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:325)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:319)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:5)
	at beam.sim.RunBeam$.main(RunBeam.scala:14)
	at beam.sim.RunBeam.main(RunBeam.scala)
:run FAILED

FAILURE: Build failed with an exception.
```

**Comment by REASY** [comment]
Already solved by https://github.com/LBNL-UCB-STI/beam/pull/2324
