### ISSUE TITLE
AgentSim on iteration 1 failing

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2405]
I'm getting a lot of exception on  the latest `develop` branch after we merged https://github.com/LBNL-UCB-STI/beam/pull/2402:
```
00:43:42.226 ERROR akka.actor.OneForOneStrategy - Trying to set a driver where there already is one.
java.lang.RuntimeException: Trying to set a driver where there already is one.
	at beam.agentsim.agents.vehicles.BeamVehicle.becomeDriver(BeamVehicle.scala:118)
	at beam.agentsim.agents.household.HouseholdActor$HouseholdActor$$anonfun$receive$1.$anonfun$applyOrElse$6(HouseholdActor.scala:202)
	at beam.agentsim.agents.household.HouseholdActor$HouseholdActor$$anonfun$receive$1.$anonfun$applyOrElse$6$adapted(HouseholdActor.scala:182)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at beam.agentsim.agents.household.HouseholdActor$HouseholdActor$$anonfun$receive$1.applyOrElse(HouseholdActor.scala:182)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at beam.agentsim.agents.household.HouseholdActor$HouseholdActor.aroundReceive(HouseholdActor.scala:114)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
	at akka.actor.ActorCell.invoke(ActorCell.scala:579)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
The fix is pretty simple:  we should reset the state of `BeamScenario.privateVehicles` in the end of every iteration

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2406
