### ISSUE TITLE
Grafana: with urbansim-100k java.util.concurrent.TimeoutException when calculating RH-EV-CAV metrics

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#2411]
because of calculation of RH-EV-CAV metrics in src/main/scala/beam/analysis/RideHailFleetAnalysis.scala
with config test/input/sf-light/urbansim-100k.conf 
BEAM run was interrupted by error: java.util.concurrent.TimeoutException

When collecting RH-EV-CAV metrics turned off and class RideHailFleetAnalysis does not created then BEAM run proceed fine.

**Comment by nikolayilyin** [comment]
[beamLog.zip](https://github.com/LBNL-UCB-STI/beam/files/4362903/beamLog.zip)

**Comment by nikolayilyin** [comment]
`[main] ERROR o.m.c.controler.AbstractController - Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.util.concurrent.TimeoutException: Futures timed out after [1000 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at beam.sim.LoggingEventsManager.$anonfun$finishProcessing$1(LoggingEventsManager.scala:86)
	at beam.sim.LoggingEventsManager.$anonfun$finishProcessing$1$adapted(LoggingEventsManager.scala:84)
	at scala.Option.foreach(Option.scala:407)
	at beam.sim.LoggingEventsManager.finishProcessing(LoggingEventsManager.scala:84)
	at beam.sim.BeamMobsim.run(BeamMobsim.scala:132)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:111)
	at org.matsim.core.controler.AbstractController$7.run(AbstractController.java:192)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:188)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:147)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:28)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy22.run(Unknown Source)
	at beam.sim.BeamHelper.run(BeamHelper.scala:712)
	at beam.sim.BeamHelper.run$(BeamHelper.scala:711)
	at beam.sim.RunBeam$.run(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:585)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:563)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:508)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:473)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:336)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:330)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:5)
	at beam.sim.RunBeam$.main(RunBeam.scala:14)
	at beam.sim.RunBeam.main(RunBeam.scala)`

**Comment by nikolayilyin** [comment]
accidentally was fixed during a review of https://github.com/LBNL-UCB-STI/beam/pull/2269
