### ISSUE TITLE
InfluxDbSimulationMetricCollector: Waits for one minute to close connection if it was not opened

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2461]
When run the latest test/input/beamville/beam.conf on 43420147d9313a23d812476539165ba29a6a0157, I see the following:
```
22:09:01.312 INFO  beam.sim.BeamSim - Renaming file - output_vehicles.xml.gz to follow camel case notation : C:\repos\beam\output\beamville\beamville__2020-03-27_22-06-54_gws\outputVehicles.xml.gz
22:09:59.709 INFO  b.s.m.InfluxDbSimulationMetricCollector - Following metrics was disabled: rh-noev-nocav-count,ride-hail-inquiry-served,ride-hail-allocation-failed,rh-ev-nocav-count,rh-noev-cav-count,rh-ev-cav-count,rh-ev-cav-distance,rh-noev-nocav-distance,rh-ev-nocav-distance,ride-hail-inquiry-not-available,rh-noev-cav-distance,ride-hail-allocation-reserved
22:09:59.709 INFO  b.s.m.InfluxDbSimulationMetricCollector - Following metrics was enabled: average-travel-time,beam-run-population-size,beam-run-RH-non-ev-non-cav,beam-run-charging-depots-stalls-cnt,beam-run-public-fast-charge-stalls-cnt,beam-run,chargingPower,beam-run-households,ride-hail-waiting-time-map,beam-run-private-fleet-size,mode-choices,beam-run-charging-depots-cnt,ride-hail-trip-distance,beam-run-public-fast-charge-cnt,parking,beam-iteration,ride-hail-waiting-time,beam-run-RH-non-ev-cav,beam-run-RH-ev-cav,beam-run-RH-ev-non-cav
22:09:59.758 INFO  beam.sim.RunBeam$ - Exiting BEAM
```
Thread dump points to the main method which waits for connection:
```
"main" #1 prio=5 os_prio=0 tid=0x0000000002722800 nid=0x5c94 runnable [0x000000000253b000]
   java.lang.Thread.State: RUNNABLE
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	- locked <0x00000007227c6308> (a java.net.DualStackPlainSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at org.influxdb.impl.BasicAuthInterceptor.intercept(BasicAuthInterceptor.java:22)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:152)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:813)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:460)
	at org.influxdb.impl.RetryCapableBatchWriter.tryToWrite(RetryCapableBatchWriter.java:127)
	at org.influxdb.impl.RetryCapableBatchWriter.close(RetryCapableBatchWriter.java:118)
	- locked <0x00000005c2109938> (a org.influxdb.impl.RetryCapableBatchWriter)
	at org.influxdb.impl.BatchProcessor.flushAndShutdown(BatchProcessor.java:384)
	at org.influxdb.impl.InfluxDBImpl.disableBatch(InfluxDBImpl.java:367)
	at org.influxdb.impl.InfluxDBImpl.close(InfluxDBImpl.java:846)
	at beam.sim.metrics.InfluxDbSimulationMetricCollector.$anonfun$close$4(SimulationMetricCollector.scala:302)
	at beam.sim.metrics.InfluxDbSimulationMetricCollector.$anonfun$close$4$adapted(SimulationMetricCollector.scala:302)
	at beam.sim.metrics.InfluxDbSimulationMetricCollector$$Lambda$3161/401876843.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at beam.sim.metrics.InfluxDbSimulationMetricCollector.$anonfun$close$3(SimulationMetricCollector.scala:302)
	at beam.sim.metrics.InfluxDbSimulationMetricCollector$$Lambda$3160/1181745921.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at beam.sim.metrics.InfluxDbSimulationMetricCollector.close(SimulationMetricCollector.scala:302)
	at beam.sim.BeamSim.notifyShutdown(BeamSim.scala:431)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerShutdownEvent(ControlerListenerManagerImpl.java:127)
	at org.matsim.core.controler.AbstractController$1.shutdown(AbstractController.java:89)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:66)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy21.run(Unknown Source)
	at beam.sim.BeamHelper.run(BeamHelper.scala:696)
	at beam.sim.BeamHelper.run$(BeamHelper.scala:695)
	at beam.sim.RunBeam$.run(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:569)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:547)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:492)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:457)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:339)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:333)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:5)
	at beam.sim.RunBeam$.main(RunBeam.scala:14)
	at beam.sim.RunBeam.main(RunBeam.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:66)
```
It has something to do with one of these parameters: https://github.com/square/okhttp/blob/okhttp_3.14.x/okhttp/src/main/java/okhttp3/OkHttpClient.java#L468-L470

But why do we even try to close something if it was not available? Is there a way to check the connection?
Seems like we can use `ping` method to do it.

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2462
