### ISSUE TITLE
Bug: actor name [BeamMobsim.iteration] is not unique!

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2514]
During CI got an exception that [actor name is not unique](https://beam-ci.tk/job/beam-forced-prs/2137/consoleFull):
```
00:23:26 A PersonAgent
00:23:26 - should allow scheduler to set the first activity (9 milliseconds)
00:23:26 - should demonstrate a complete trip, throwing MATSim events (80 milliseconds)
00:23:26 - should know how to take a walk_transit trip when it's already in its plan (29 milliseconds)
00:23:26 17:23:26.235 [PersonAgentSpec-akka.actor.default-dispatcher-5] ERROR beam.agentsim.agents.PersonAgent - BeamAgent Got Shutdown. This means actorRef.stop() was called externally, e.g. by supervisor because of an exception. In state PerformingActivity
00:23:26 
00:23:26 17:23:26.235 [PersonAgentSpec-akka.actor.default-dispatcher-5] ERROR beam.agentsim.agents.PersonAgent - State: PerformingActivity Event: StopEvent(Shutdown,PerformingActivity,BasePersonData(0,None,List(),Vector(),None,None,,0,false,0.0,0,None))
00:23:26 17:23:26.235 [PersonAgentSpec-akka.actor.default-dispatcher-14] ERROR beam.agentsim.agents.PersonAgent - Events leading up to this point:
00:23:26 	LogEntry(Uninitialized,BasePersonData(0,None,List(),Vector(),None,None,,0,false,0.0,0,None),TriggerWithId(InitializeTrigger(0),1))
00:23:26 	LogEntry(Initialized,BasePersonData(0,None,List(),Vector(),None,None,,0,false,0.0,0,None),TriggerWithId(ActivityStartTrigger(0),2))
00:23:26 	LogEntry(PerformingActivity,BasePersonData(0,None,List(),Vector(),None,None,,0,false,0.0,0,None),TriggerWithId(ActivityEndTrigger(10),3))
00:23:26 - should also work when the first bus is late *** FAILED *** (4 milliseconds)
00:23:26   akka.actor.InvalidActorNameException: actor name [BeamMobsim.iteration] is not unique!
00:23:26   at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:134)
00:23:26   at akka.actor.dungeon.Children.reserveChild(Children.scala:137)
00:23:26   at akka.actor.dungeon.Children.reserveChild$(Children.scala:135)
00:23:26   at akka.actor.ActorCell.reserveChild(ActorCell.scala:445)
00:23:26   at akka.testkit.TestActorRef.<init>(TestActorRef.scala:28)
00:23:26   at akka.testkit.TestActorRef$.apply(TestActorRef.scala:161)
00:23:26   at akka.testkit.TestActorRef$.apply(TestActorRef.scala:151)
00:23:26   at beam.agentsim.agents.PersonAgentSpec.$anonfun$new$15(PersonAgentSpec.scala:535)
00:23:26   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
00:23:26   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```
Issue at akka github: https://github.com/akka/akka/issues/24165#issuecomment-360046650. I understand it like we shouldn't have the same actor name across different test, but in our test we violate this rule.

@JustinPihony  what do you think?

**Comment by REASY** [comment]
Started a draft PR: https://github.com/LBNL-UCB-STI/beam/pull/2517, but now it fails with other exceptions. We have a dependency in the actor path and I guess it causes this problem.

**Comment by REASY** [comment]
@dimaopen I've got this exception again:
```
23:56:40 - should know how to take a walk_transit trip when it's already in its plan *** FAILED *** (202 milliseconds)
23:56:40   java.lang.AssertionError: assertion failed: expected class beam.router.BeamRouter$RoutingRequest, found class beam.agentsim.scheduler.BeamAgentScheduler$CompletionNotice (CompletionNotice(0,Vector()))
23:56:40   at scala.Predef$.assert(Predef.scala:223)
23:56:40   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:531)
23:56:40   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:502)
23:56:40   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:501)
23:56:40   at beam.agentsim.agents.PersonAgentSpec.expectMsgType(PersonAgentSpec.scala:42)
23:56:40   at beam.agentsim.agents.PersonAgentSpec.$anonfun$new$9(PersonAgentSpec.scala:399)
23:56:40   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
23:56:40   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
23:56:40   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
23:56:40   at org.scalatest.Transformer.apply(Transformer.scala:22)
23:56:40   ...
23:56:40 - should also work when the first bus is late *** FAILED *** (12 milliseconds)
23:56:40   akka.actor.InvalidActorNameException: actor name [BeamMobsim.iteration] is not unique!
23:56:40   at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:134)
23:56:40   at akka.actor.dungeon.Children.reserveChild(Children.scala:137)
23:56:40   at akka.actor.dungeon.Children.reserveChild$(Children.scala:135)
23:56:40   at akka.actor.ActorCell.reserveChild(ActorCell.scala:445)
23:56:40   at akka.testkit.TestActorRef.<init>(TestActorRef.scala:28)
23:56:40   at akka.testkit.TestActorRef$.apply(TestActorRef.scala:161)
23:56:40   at akka.testkit.TestActorRef$.apply(TestActorRef.scala:151)
23:56:40   at beam.agentsim.agents.PersonAgentSpec.$anonfun$new$15(PersonAgentSpec.scala:543)
23:56:40   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
23:56:40   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```


Link to CI: https://beam-ci.tk/job/beam-forced-prs/2216/consoleFull
Attached it to the comment in case if link is outdated: [consoleText.txt.gz](https://github.com/LBNL-UCB-STI/beam/files/4553304/consoleText.txt.gz)
