### ISSUE TITLE
PhysSim fails in develop branch, commit 58069c5a3f55df1d5ed2cd8e1a05c0794d134870

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2583]
scenario: test/input/beamville/beam.conf
commit: 58069c5a3f55df1d5ed2cd8e1a05c0794d134870
error:
```
22:41:42.304 INFO  b.a.a.r.RideHailIterationsStatsCollector - 10 rideHail vehicles (out of 12) were never moved and 2 vehicles were moved without a passenger, during whole day.
22:41:42.306 INFO  beam.router.RouteHistory - Overall cache hits 72/94 (77%)
22:41:42.308 ERROR o.m.c.c.MatsimRuntimeModifications - Getting uncaught Exception in Thread main
java.util.NoSuchElementException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1447)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at java.util.Collections.max(Collections.java:671)
	at beam.analysis.physsim.PhyssimSpeedHandler.writeIterationGraph(PhyssimSpeedHandler.java:113)
	at beam.analysis.physsim.PhyssimSpeedHandler.notifyIterationEnds(PhyssimSpeedHandler.java:106)
	at beam.physsim.jdeqsim.JDEQSimRunner.simulate(JDEQSimRunner.scala:129)
	at beam.physsim.jdeqsim.PhysSim.run(PhysSim.scala:102)
	at beam.physsim.jdeqsim.PhysSim.run(PhysSim.scala:67)
	at beam.physsim.jdeqsim.Normal.run(RelaxationExperiment.scala:208)
	at beam.physsim.jdeqsim.AgentSimToPhysSimPlanConverter.setupActorsAndRunPhysSim(AgentSimToPhysSimPlanConverter.java:145)
	at beam.physsim.jdeqsim.AgentSimToPhysSimPlanConverter.startPhysSim(AgentSimToPhysSimPlanConverter.java:419)
	at beam.sim.BeamSim.$anonfun$notifyIterationEnds$9(BeamSim.scala:316)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:64)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
22:41:42.309 ERROR o.m.c.c.MatsimRuntimeModifications - ERROR --- This is an unexpected shutdown!
```

**Comment by JustinPihony** [comment]
Closed by #2584
