### ISSUE TITLE
The test "EventsFileSpec" sometimes fails on develop

### ISSUE THREAD

**Issue by haitamlaarabi** [LBNL-UCB-STI/beam#2601]
once in ~8 times the test "EventsFileSpec" fails at the following assert:

https://github.com/LBNL-UCB-STI/beam/blob/25d5b5490fe04692972318a91b849c26c8494ae8/src/test/scala/beam/integration/EventsFileSpec.scala#L179

```
0 equaled 0 At least some people must go by bike
ScalaTestFailureLocation: beam.integration.EventsFileSpec at (EventsFileSpec.scala:179)
org.scalatest.exceptions.TestFailedException: 0 equaled 0 At least some people must go by bike
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
	at org.scalatest.FlatSpec.newAssertionFailedException(FlatSpec.scala:1685)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:503)
	at beam.integration.EventsFileSpec.$anonfun$new$12(EventsFileSpec.scala:179)
```

**Comment by rajnikantsh** [comment]
closed via https://github.com/LBNL-UCB-STI/beam/pull/2588
