### ISSUE TITLE
CI: Failured test in BeamFederateSpec

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2830]
Link to the logs: https://beam-ci.tk/job/beam-forced-prs/2538/consoleFull
```
BeamFederateSpec:
14:52:24 Running a beamville scenario with cosimulation
14:52:24 - must result event being published and read *** FAILED *** (9 seconds, 655 milliseconds)
14:52:24   java.lang.Exception: broker responded with error: already in initialization mode
14:52:24   at com.java.helics.helicsJNI.helicsCreateCombinationFederate(Native Method)
14:52:24   at com.java.helics.helics.helicsCreateCombinationFederate(helics.java:464)
14:52:24   at beam.cosim.helics.BeamFederateSpec.createBrokerAndReaderFederate(BeamFederateSpec.scala:81)
14:52:24   at beam.cosim.helics.BeamFederateSpec.$anonfun$new$2(BeamFederateSpec.scala:35)
14:52:24   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
14:52:24   at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
14:52:24   at scala.util.Success.$anonfun$map$1(Try.scala:255)
14:52:24   at scala.util.Success.map(Try.scala:213)
14:52:24   at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
14:52:24   at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
14:52:24   ...
```

**Comment by REASY** [comment]
Some comments from @haitamlaarabi:
```
the real problem is the broker create in:
val broker = helics.helicsCreateBroker("zmq", "", s"-f 2 --name=BeamBrokerTemp")
just check if verifying a broker exist after before/after creation (or the core) would work
```
![image](https://user-images.githubusercontent.com/5107562/88403640-00aa5300-cdf7-11ea-9fa3-281427c00be1.png)
