### ISSUE TITLE
Tests: Helics native library does not allow Java process to exit (Windows only?)

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2837]
Is there any resource which is not freed? Or because during the initialization the following exception happened?
```
19:34:35.577 [ClusterSystem-akka.actor.default-dispatcher-16] ERROR akka.actor.OneForOneStrategy - java.io.FileNotFoundException: C:\Users\User\AppData\Local\Temp\helics\helicsJava.dll (The process cannot access the file because it is being used by another process)
akka.actor.ActorInitializationException: akka://ClusterSystem/user/BeamMobsim.iteration/$c: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
	at akka.actor.ActorCell.create(ActorCell.scala:661)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\User\AppData\Local\Temp\helics\helicsJava.dll (The process cannot access the file because it is being used by another process)
	at com.github.beam.HelicsLoader.unzipLibArchive(HelicsLoader.java:61)
	at com.github.beam.HelicsLoader.load(HelicsLoader.java:24)
	at helics.BeamFederate$.getInstance(BeamFederate.scala:21)
	at beam.agentsim.agents.vehicles.EventsAccumulator.<init>(EventsAccumulator.scala:26)
	at beam.agentsim.agents.vehicles.EventsAccumulator$.$anonfun$props$1(EventsAccumulator.scala:18)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:91)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:613)
	at akka.actor.ActorCell.create(ActorCell.scala:640)
	... 9 common frames omitted
Caused by: java.io.FileNotFoundException: C:\Users\User\AppData\Local\Temp\helics\helicsJava.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.github.beam.HelicsLoader.unzipLibArchive(HelicsLoader.java:48)
	... 17 common frames omitted
```

Should we allow to have temporary folder instead of static folder in temp folder for helics-wrapper?
https://github.com/LBNL-UCB-STI/helics-wrapper/blob/0f718c87c7cd5fbb0fe772e4534cb00e9fbd5ac5/src/main/java/com.github.beam/HelicsLoader.java#L17

![image](https://user-images.githubusercontent.com/5107562/87308064-dd54ed80-c544-11ea-875d-48d5bc6d9c1b.png)

![image](https://user-images.githubusercontent.com/5107562/87307984-be565b80-c544-11ea-968d-13c3bd0ac830.png)

**Comment by SHaaD94** [comment]
Please try to add the following in tests:
```
com.java.helics.helics.helicsCleanupLibrary()
com.java.helics.helics.helicsCloseLibrary()
```

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2832
