### ISSUE TITLE
Parallel test running locally: different failing test from run to run

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2838]
Local run of parallel test via `build -PnumThreads=10 --info` and we have some failed tests:

UrbanSimRun
```
UrbanSimRun
- must run  urbansim-1k.conf *** FAILED *** (2 minutes, 53 seconds)
  java.lang.NullPointerException:
  at com.sun.xml.bind.v2.runtime.Coordinator.popCoordinator(Coordinator.java:162)
  at com.sun.xml.bind.v2.runtime.XMLSerializer.close(XMLSerializer.java:860)
  at com.sun.xml.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:329)
  at com.sun.xml.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:249)
  at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:116)
  at org.matsim.vis.kml.KMZWriter.writeKml(KMZWriter.java:235)
  at org.matsim.vis.kml.KMZWriter.writeMainKml(KMZWriter.java:147)
  at org.matsim.counts.algorithms.CountSimComparisonKMLWriter.finish(CountSimComparisonKMLWriter.java:1048)
  at org.matsim.counts.algorithms.CountSimComparisonKMLWriter.writeFile(CountSimComparisonKMLWriter.java:396)
  at org.matsim.counts.CountsControlerListener.notifyIterationEnds(CountsControlerListener.java:145)
  ...
```

BeamWarmStartRunSpec
```
BeamWarmStartRunSpec:
Beam WarmStart
- must run sf-light scenario for two iteration with warmstart *** FAILED *** (2 minutes, 44 seconds)
  java.util.EmptyStackException:
  at java.util.Stack.peek(Stack.java:102)
  at java.util.Stack.pop(Stack.java:84)
  at com.sun.xml.bind.marshaller.DataWriter.endElement(DataWriter.java:282)
  at com.sun.xml.bind.v2.runtime.output.SAXOutput.endTag(SAXOutput.java:132)
  at com.sun.xml.bind.v2.runtime.output.XmlOutputAbstractImpl.endTag(XmlOutputAbstractImpl.java:124)
  at com.sun.xml.bind.v2.runtime.XMLSerializer.leafElement(XMLSerializer.java:330)
  at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$StringImplImpl.writeLeafElement(RuntimeBuiltinLeafInfoImpl.java:1045)
  at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$StringImplImpl.writeLeafElement(RuntimeBuiltinLeafInfoImpl.java:1024)
  at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.writeLeafElement(TransducedAccessor.java:256)
  at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.serializeBody(SingleElementLeafProperty.java:128)
  ...
```

EventsFileSpec:
```
EventsFileSpec:
- should contain the same bus trips entries *** FAILED *** (96 milliseconds)
  Set("B1-WEST-1", "B3-EAST-1", "B2-WEST-1", "B3-WEST-1", "B2-EAST-1") did not contain the same elements as Set("B1-WEST-1", "B1-EAST-1", "B3-EAST-1", "B2-WEST-1", "B3-WEST-1", "B2-EAST-1") (EventsFileSpec.scala:70)
- should contain the same train trips entries (125 milliseconds)
- should contain same pathTraversal defined at stop times file for bus input file *** FAILED *** (111 milliseconds)
  Set("B1-WEST-1", "B3-EAST-1", "B2-WEST-1", "B3-WEST-1", "B2-EAST-1") did not contain the same elements as Set("B1-WEST-1", "B1-EAST-1", "B3-EAST-1", "B2-WEST-1", "B3-WEST-1", "B2-EAST-1") (EventsFileSpec.scala:96)
- should contain same pathTraversal defined at stop times file for train input file (164 milliseconds)
- should also be available as csv file (0 milliseconds)
- should contain at least one paid toll (197 milliseconds)
- should yield positive toll revenue according to TollRevenueAnalysis (157 milliseconds)
- should also produce experienced plans which make sense (444 milliseconds)
- should contain PhysSim events (18 milliseconds)
```

[beamLog.out.gz](https://github.com/LBNL-UCB-STI/beam/files/4913603/beamLog.out.gz)

Two failed tests `UrbanSimRun` and `BeamWarmStartRunSpec` are because one of the components uses static fields: https://github.com/wrashid/matsim/blob/1ea7bf3aa1d5c4eab46f0a02ed392fd475ac1e25/matsim/src/main/java/org/matsim/vis/kml/KMZWriter.java#L65-L67

**Comment by REASY** [comment]
The fix for KMZWriter: https://github.com/wrashid/matsim/pull/10
Release for MATSim: https://github.com/wrashid/matsim/releases/tag/0.10.1-beam-15

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2839
https://github.com/LBNL-UCB-STI/beam/pull/2836

**Comment by JustinPihony** [comment]
@REASY both referenced items are merged, can this be closed?

**Comment by REASY** [comment]
@JustinPihony I tried to run run CI on develop branch multiple times and got failed test: 
![image](https://user-images.githubusercontent.com/5107562/87873191-a752b600-c9e9-11ea-828d-3d682847f82a.png)
Link to failed builds:
- https://beam-ci.tk/job/develop/483/consoleFull
- https://beam-ci.tk/job/develop/482/consoleFull

Both of them have `BeamFederateSpec` failed:
```
21:46:47 BeamFederateSpec:
21:46:47 Running a beamville scenario with cosimulation
21:46:47 - must result event being published and read *** FAILED *** (14 seconds, 372 milliseconds)
21:46:47   java.lang.IllegalArgumentException: requirement failed
21:46:47   at scala.Predef$.require(Predef.scala:268)
21:46:47   at beam.cosim.helics.BeamFederateSpec.$anonfun$new$1(BeamFederateSpec.scala:56)
21:46:47   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
21:46:47   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
21:46:47   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
21:46:47   at org.scalatest.Transformer.apply(Transformer.scala:22)
21:46:47   at org.scalatest.Transformer.apply(Transformer.scala:20)
21:46:47   at org.scalatest.FlatSpecLike$$anon$5.apply(FlatSpecLike.scala:1682)
21:46:47   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
21:46:47   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
21:46:47   ...
```
So our CI is still unstable...

**Comment by JustinPihony** [comment]
Okie :)
