### ISSUE TITLE
Charging: java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2844]
branch: develop
commit: 7ce92a45b87bd80bda17dd45775716af6fbbb3ca
config: test/input/sf-light/sf-light-1k.conf

```
22:54:24.472 INFO  b.a.scheduler.BeamAgentScheduler - Hour 19.0 completed. 8.0(GB)
22:54:24.667 ERROR akka.actor.OneForOneStrategy - None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at beam.agentsim.agents.modalbehaviors.DrivesVehicle.handleEndCharging(DrivesVehicle.scala:896)
	at beam.agentsim.agents.modalbehaviors.DrivesVehicle.handleEndCharging$(DrivesVehicle.scala:874)
	at beam.agentsim.agents.PersonAgent.handleEndCharging(PersonAgent.scala:233)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.$anonfun$applyOrElse$3(PersonAgent.scala:447)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.$anonfun$applyOrElse$3$adapted(PersonAgent.scala:445)
	at scala.Option.foreach(Option.scala:407)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.$anonfun$applyOrElse$2(PersonAgent.scala:445)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.$anonfun$applyOrElse$2$adapted(PersonAgent.scala:442)
	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.applyOrElse(PersonAgent.scala:442)
	at beam.agentsim.agents.PersonAgent$$anonfun$3.applyOrElse(PersonAgent.scala:434)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at akka.actor.FSM.processEvent(FSM.scala:804)
	at akka.actor.FSM.processEvent$(FSM.scala:801)
	at beam.agentsim.agents.PersonAgent.akka$actor$LoggingFSM$$super$processEvent(PersonAgent.scala:233)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:944)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:926)
	at beam.agentsim.agents.PersonAgent.processEvent(PersonAgent.scala:233)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:793)
	at akka.actor.Actor.aroundReceive(Actor.scala:535)
	at akka.actor.Actor.aroundReceive$(Actor.scala:533)
	at beam.agentsim.agents.PersonAgent.aroundReceive(PersonAgent.scala:233)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by JustinPihony** [comment]
This is pretty much the same thing as https://github.com/LBNL-UCB-STI/beam/pull/2374 - I'm thinking it is time to fix the Vehicle. The lock was a band-aid.
