### ISSUE TITLE
SimpleScenarioGenerator: Exception during the generation of New York scenario

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2927]
Exception:
```
10:17:30.974 INFO  b.u.d.s.SimpleScenarioGenerator - BlockGroupGeoId(State(36),County(081),058300,2) contains 392 households. 11552 out of 11553, pct: 99.991%
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:529)
        at scala.None$.get(Option.scala:527)
        at scala.collection.parallel.ParIterableLike.$anonfun$min$1(ParIterableLike.scala:481)
        at scala.collection.parallel.ParIterableLike$$anon$1$$anon$2.map(ParIterableLike.scala:308)
        at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:961)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
        at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:955)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/commit/aefaf56034fd6376bb00dff82ae8a4cd4c3654ad

**Comment by JustinPihony** [comment]
Another that is not in develop per the PR you referenced. I'll stop pinging on these until I hear back
