### ISSUE TITLE
Beam docker: Austin run throws FileNotFoundException exception

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2945]
I'm running Beam in Docker on Windows 10. Also it is Austin scenario which contains secondary activities. Most probably we have two activity type which is differs only in the case (upper or lower case, `work` and `Work`). Here is the content of that folder:
![image](https://user-images.githubusercontent.com/5107562/91448996-ca07a280-e8a4-11ea-8caa-fdb668b3f349.png)

Need to check all possible activity types from the input.
```
13:15:51.112 ERROR o.m.c.c.MatsimRuntimeModifications - ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
13:15:51.112 ERROR o.m.c.c.MatsimRuntimeModifications - ERROR --- results should not be used for further analysis.
13:15:51.112 ERROR o.m.c.c.MatsimRuntimeModifications - ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /app/output/austin/austin-prod-200k-flowCap-0.2-speedScaling-1.1__2020-08-27_13-06-12_fzp/summaryStats/averageTripExpenditure/averageTripExpenditure_work.png (File exists)
        at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:98)
        at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
        at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
        at org.matsim.core.controler.NewControler.run(NewControler.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at com.sun.proxy.$Proxy22.run(Unknown Source)
        at beam.sim.BeamHelper.run(BeamHelper.scala:762)
        at beam.sim.BeamHelper.run$(BeamHelper.scala:761)
        at beam.sim.RunBeam$.run(RunBeam.scala:8)
        at beam.sim.BeamHelper.runBeam(BeamHelper.scala:593)
        at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:571)
        at beam.sim.RunBeam$.runBeam(RunBeam.scala:8)
        at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:477)
        at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:465)
        at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:8)
        at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:335)
        at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:329)
        at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:8)
        at beam.sim.RunBeam$.main(RunBeam.scala:23)
        at beam.sim.RunBeam.main(RunBeam.scala)
Caused by: java.io.FileNotFoundException: /app/output/austin/austin-prod-200k-flowCap-0.2-speedScaling-1.1__2020-08-27_13-06-12_fzp/summaryStats/averageTripExpenditure/averageTripExpenditure_work.png (File exists)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.jfree.chart.ChartUtilities.saveChartAsPNG(ChartUtilities.java:308)
        at org.jfree.chart.ChartUtilities.saveChartAsPNG(ChartUtilities.java:285)
        at beam.analysis.plots.GraphUtils.saveJFreeChartAsPNG(GraphUtils.java:171)
        at beam.sim.BeamSim.createGraph(BeamSim.scala:663)
        at beam.sim.BeamSim.$anonfun$createSummaryStatsGraph$2(BeamSim.scala:621)
        at beam.sim.BeamSim.$anonfun$createSummaryStatsGraph$2$adapted(BeamSim.scala:614)
        at scala.collection.mutable.HashMap$$anon$1.$anonfun$foreach$2(HashMap.scala:153)
        at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
        at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
        at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:153)
        at beam.sim.BeamSim.createSummaryStatsGraph(BeamSim.scala:614)
        at beam.sim.BeamSim.$anonfun$notifyIterationEnds$12(BeamSim.scala:367)
        at beam.sim.BeamSim.$anonfun$notifyIterationEnds$12$adapted(BeamSim.scala:367)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:38)
        at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:38)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:47)
        at beam.sim.BeamSim.$anonfun$notifyIterationEnds$11(BeamSim.scala:367)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at beam.utils.watcher.MethodWatcher$.withLoggingInvocationTime(MethodWatcher.scala:15)
        at beam.sim.BeamSim.$anonfun$notifyIterationEnds$3(BeamSim.scala:365)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by REASY** [comment]
dd3c3b9a8c2c976fdbbdca2941daea01195bb9ce

**Comment by JustinPihony** [comment]
Per the commit you referenced this was only pushed to a branch which seems as though it will not be merged (https://github.com/LBNL-UCB-STI/beam/pull/2946), is that correct?
