### ISSUE TITLE
Tests: Pass spec name to the actor system for easier debugging

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2976]
There are exceptions in our CI on develop branch, but tests has passed: https://beam-ci.tk/job/develop/541/consoleFull
```
09:59:52 java.lang.NumberFormatException: For input string: "scripts"
09:59:53 02:59:53.359 [ScalaTest-1-running-UrbanSimRunSpec] ERROR b.s.p.DefaultPopulationAdjustment - Not all agents have person attributes - is attributes file missing ?
09:59:53 02:59:53.474 [ClusterSystem-akka.actor.default-dispatcher-21] ERROR beam.sim.monitoring.ErrorListener - ErrorListener: saw dead letter without knowing how to handle it: DeadLetter(Finish,Actor[akka://ClusterSystem/user/BeamMobsim.iteration#-45907706],Actor[akka://ClusterSystem/user/BeamMobsim.iteration/RideHailManager#-1442958959])
09:59:54 02:59:54.100 [ClusterSystem-akka.actor.default-dispatcher-21] ERROR akka.actor.OneForOneStrategy - transit_walk is not a member of ValueEnum (car, cav, ride_hail, ride_hail_pooled, bus, funicular, gondola, cable_car, ferry, transit, rail, subway, tram, walk, bike, walk_transit, drive_transit, ride_hail_transit)
09:59:54 akka.actor.ActorInitializationException: akka://ClusterSystem/user/BeamMobsim.iteration/population/11/25: exception during creation
09:59:54 	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
09:59:54 	at akka.actor.ActorCell.create(ActorCell.scala:661)
09:59:54 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
09:59:54 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
09:59:54 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
09:59:54 	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
09:59:54 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
09:59:54 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
09:59:54 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
09:59:54 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
09:59:54 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
09:59:54 Caused by: java.util.NoSuchElementException: transit_walk is not a member of ValueEnum (car, cav, ride_hail, ride_hail_pooled, bus, funicular, gondola, cable_car, ferry, transit, rail, subway, tram, walk, bike, walk_transit, drive_transit, ride_hail_transit)
09:59:54 	at enumeratum.values.ValueEnum.$anonfun$withValue$1(ValueEnum.scala:58)
09:59:54 	at scala.Option.getOrElse(Option.scala:189)
09:59:54 	at enumeratum.values.ValueEnum.withValue(ValueEnum.scala:58)
09:59:54 	at enumeratum.values.ValueEnum.withValue$(ValueEnum.scala:57)
09:59:54 	at beam.router.Modes$BeamMode$.withValue(Modes.scala:47)
09:59:54 	at beam.router.Modes$BeamMode$.fromString(Modes.scala:137)
09:59:54 	at beam.agentsim.agents.planning.BeamPlan.$anonfun$createToursFromMatsimPlan$2(BeamPlan.scala:130)
09:59:54 	at beam.agentsim.agents.planning.BeamPlan.$anonfun$createToursFromMatsimPlan$2$adapted(BeamPlan.scala:128)
09:59:54 	at scala.collection.Iterator.foreach(Iterator.scala:943)
09:59:54 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
09:59:54 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
09:59:54 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
09:59:54 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
09:59:54 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
09:59:54 	at beam.agentsim.agents.planning.BeamPlan.createToursFromMatsimPlan(BeamPlan.scala:128)
09:59:54 	at beam.agentsim.agents.planning.BeamPlan$.apply(BeamPlan.scala:45)
09:59:54 	at beam.agentsim.agents.PersonAgent.<init>(PersonAgent.scala:275)
09:59:54 	at beam.agentsim.agents.PersonAgent$.$anonfun$props$1(PersonAgent.scala:92)
09:59:54 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:91)
09:59:54 	at akka.actor.Props.newActor(Props.scala:226)
09:59:54 	at akka.actor.ActorCell.newActor(ActorCell.scala:613)
09:59:54 	at akka.actor.ActorCell.create(ActorCell.scala:640)
09:59:54 	... 9 common frames omitted
```
The test are running in parallel and it is hard to know in which test this exception happen. Let's propagate spec name to the ActorSystem name, so instead of 09:59:53 02:59:53.474 [**ClusterSystem**-akka.actor.default-dispatcher-21] there will be the name of the spec. Keep in mind the following constants:
- https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/sim/modules/BeamAgentModule.scala#L19
- https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/sim/BeamHelper.scala#L456

The only affected are the tests which starts simulation manually

**Comment by carloscaldas** [comment]
Errors are at MultinomialCustomConfigSpec. Tests:
```
- Prefer mode car when intercept is very high versus very low
- Prefer mode ride_hail when intercept is very high versus very low
```
