### ISSUE TITLE
Improve tests: other is not a member of ValueEnum

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3041]
Link to CI: https://beam-ci.tk/job/beam-forced-prs/2816/consoleFull
Exception occurs in `SkimmerSpec`
```
23:05:02 UrbanSimRunSpec:
23:05:02 UrbanSimRun
23:05:08 16:05:08.007 [ClusterSystem-akka.actor.default-dispatcher-27] ERROR akka.actor.OneForOneStrategy - other is not a member of ValueEnum (car, cav, ride_hail, ride_hail_pooled, bus, funicular, gondola, cable_car, ferry, transit, rail, subway, tram, walk, bike, walk_transit, drive_transit, ride_hail_transit)
23:05:08 akka.actor.ActorInitializationException: akka://ClusterSystem/user/BeamMobsim.iteration/population/1/3: exception during creation
23:05:08 	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
23:05:08 	at akka.actor.ActorCell.create(ActorCell.scala:661)
23:05:08 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
23:05:08 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
23:05:08 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
23:05:08 	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
23:05:08 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
23:05:08 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
23:05:08 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
23:05:08 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
23:05:08 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
23:05:08 Caused by: java.util.NoSuchElementException: other is not a member of ValueEnum (car, cav, ride_hail, ride_hail_pooled, bus, funicular, gondola, cable_car, ferry, transit, rail, subway, tram, walk, bike, walk_transit, drive_transit, ride_hail_transit)
23:05:08 	at enumeratum.values.ValueEnum.$anonfun$withValue$1(ValueEnum.scala:58)
23:05:08 	at scala.Option.getOrElse(Option.scala:189)
23:05:08 	at enumeratum.values.ValueEnum.withValue(ValueEnum.scala:58)
23:05:08 	at enumeratum.values.ValueEnum.withValue$(ValueEnum.scala:57)
23:05:08 	at beam.router.Modes$BeamMode$.withValue(Modes.scala:47)
23:05:08 	at beam.router.Modes$BeamMode$.fromString(Modes.scala:137)
23:05:08 	at beam.agentsim.agents.planning.BeamPlan.$anonfun$createToursFromMatsimPlan$2(BeamPlan.scala:130)
23:05:08 	at beam.agentsim.agents.planning.BeamPlan.$anonfun$createToursFromMatsimPlan$2$adapted(BeamPlan.scala:128)
23:05:08 	at scala.collection.Iterator.foreach(Iterator.scala:943)
23:05:08 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
23:05:08 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
23:05:08 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
23:05:08 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
23:05:08 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
23:05:08 	at beam.agentsim.agents.planning.BeamPlan.createToursFromMatsimPlan(BeamPlan.scala:128)
23:05:08 	at beam.agentsim.agents.planning.BeamPlan$.apply(BeamPlan.scala:45)
23:05:08 	at beam.agentsim.agents.PersonAgent.<init>(PersonAgent.scala:275)
23:05:08 	at beam.agentsim.agents.PersonAgent$.$anonfun$props$1(PersonAgent.scala:92)
23:05:08 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:91)
23:05:08 	at akka.actor.Props.newActor(Props.scala:226)
23:05:08 	at akka.actor.ActorCell.newActor(ActorCell.scala:613)
23:05:08 	at akka.actor.ActorCell.create(ActorCell.scala:640)
23:05:08 	... 9 common frames omitted
```
It happens because of replanning module creates a leg with matsim mode:
![image](https://user-images.githubusercontent.com/5107562/95906456-570aaa80-0dc4-11eb-879d-2be63f938980.png)

**Comment by rajnikantsh** [comment]
closed via https://github.com/LBNL-UCB-STI/beam/pull/3060
