### ISSUE TITLE
Error trying to create a graph ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by haitamlaarabi** [LBNL-UCB-STI/beam#3234]
it happens every now and then!

`18:09:31.235 ERROR b.a.p.GraphsStatsAgentSimEventsListener - Error trying to create a graph
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at beam.analysis.plots.PersonTravelTimeAnalysis$PersonTravelTimeComputation.compute(PersonTravelTimeAnalysis.java:69)
	at beam.analysis.plots.PersonTravelTimeAnalysis$PersonTravelTimeComputation.compute(PersonTravelTimeAnalysis.java:54)
	at beam.analysis.plots.PersonTravelTimeAnalysis.compute(PersonTravelTimeAnalysis.java:165)
	at beam.analysis.plots.PersonTravelTimeAnalysis.createGraph(PersonTravelTimeAnalysis.java:142)
	at beam.analysis.plots.GraphsStatsAgentSimEventsListener.createGraphs(GraphsStatsAgentSimEventsListener.java:96)
	at beam.sim.BeamSim.$anonfun$notifyIterationEnds$4(BeamSim.scala:387)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by JustinPihony** [comment]
This is happening because `List<Integer> hoursList = stat.values().stream().flatMap(m -> m.keySet().stream()).sorted().collect(Collectors.toList());` results in an empty list. The question is what should be done here?

* Throw a more specific exception in order to trace this back further (and eventually get to the root of the issue)
* Handle an empty list and make the `maxHour` equal to 0?
* Something else?

**Comment by haitamlaarabi** [comment]
it is always better to understand the root of the issue.

**Comment by dgm90** [comment]
The root cause is that when `beam.agentsim.agentSampleSizeAsFractionOfPopulation` is relatively small, like 0.001, then there are only a few agents in simulation and this leads to the fact, that the agents choose only the **car** mode. The `beam.analysis.plots.PersonTravelTimeAnalysis#processPersonArrivalEvent` propagates the `hourlyPersonTravelTimesPerMode` map only when the mode doesn't equal to `car`. In our case this causes the map being empty and thus `java.lang.ArrayIndexOutOfBoundsException`

Fix is here #3271
