### ISSUE TITLE
Bug. ArrayIndexOutOfBoundsException during graph creation

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3288]
Beamville scenario in urbansimV2 format produce the following error while building graphs:

`12:15:06.279 ERROR b.a.p.GraphsStatsAgentSimEventsListener - Error trying to create a graph
java.lang.ArrayIndexOutOfBoundsException: 0
	at beam.analysis.plots.PersonTravelTimeAnalysis.createCSV(PersonTravelTimeAnalysis.java:182)
	at beam.analysis.plots.PersonTravelTimeAnalysis.createGraph(PersonTravelTimeAnalysis.java:169)
	at beam.analysis.plots.GraphsStatsAgentSimEventsListener.createGraphs(GraphsStatsAgentSimEventsListener.java:96)
	at beam.sim.BeamSim.$anonfun$notifyIterationEnds$5(BeamSim.scala:431)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

to reproduce:
branch: inm/#3106-teleportation-hov2-hov3 (develop merged, one fix for ArrayIndexOutOfBoundsException included)
config: test/input/beamville/beam-urbansimv2.conf
commit dff712bf8489361b1689d5f424c937c88b471d31

**Comment by dgm90** [comment]
Fixed in https://github.com/LBNL-UCB-STI/beam/pull/3290
