### ISSUE TITLE
Errors when loading parking configuration lead to stuckness 

### ISSUE THREAD

**Issue by alex-vv** [LBNL-UCB-STI/beam#3357]
https://beam-ci.tk/job/application-sfbay-separate-repos/22/console

build is stuck because BEAM doesn't properly exit after an error:

```
17:58:06 11:58:06.778 ERROR akka.actor.OneForOneStrategy - head of empty list
17:58:06 akka.actor.ActorInitializationException: akka://ClusterSystem/user/BeamMobsim.iteration: exception during creation
17:58:06 	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
17:58:06 	at akka.actor.ActorCell.create(ActorCell.scala:661)
17:58:06 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
17:58:06 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
17:58:06 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
17:58:06 	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
17:58:06 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
17:58:06 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
17:58:06 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
17:58:06 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
17:58:06 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
17:58:06 Caused by: java.util.NoSuchElementException: head of empty list
17:58:06 	at scala.collection.immutable.Nil$.head(List.scala:469)
17:58:06 	at scala.collection.immutable.Nil$.head(List.scala:466)
17:58:06 	at beam.agentsim.infrastructure.InfrastructureUtils$.buildParkingAndChargingNetworks(InfrastructureUtils.scala:114)
17:58:06 	at beam.sim.BeamMobsimIteration.<init>(BeamMobsim.scala:384)
17:58:06 	at beam.sim.BeamMobsim.$anonfun$run$5(BeamMobsim.scala:154)
17:58:06 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:91)
17:58:06 	at akka.actor.Props.newActor(Props.scala:226)
17:58:06 	at akka.actor.ActorCell.newActor(ActorCell.scala:613)
17:58:06 	at akka.actor.ActorCell.create(ActorCell.scala:640)
17:58:06 	... 9 common frames omitted
```

This is probably caused by some misconfiguration, as there are errors when loading parking configuration:

```17:58:06 11:58:06.626 INFO  b.a.i.InfrastructureUtils$ - loading stalls...
17:58:06 11:58:06.628 ERROR b.a.i.parking.ParkingZoneFileUtils$ - [1] Failed to match row of parking configuration '{pricingModel=Block, parkingType=Public, numStalls=167, chargingType=Custom(150.0|DC), feeInCents=1232.8351400000001, taz=1, ReservedFor=Any}' to expected schema
17:58:06 11:58:06.628 ERROR b.a.i.parking.ParkingZoneFileUtils$ - [2] Failed to match row of parking configuration '{pricingModel=Block, parkingType=Public, numStalls=5, chargingType=Custom(150.0|DC), feeInCents=1020.0, taz=1, ReservedFor=Any}' to expected schema
...
```

**Comment by nikolayilyin** [comment]
This should be fixed by #3524
