### ISSUE TITLE
MATSim Conversion Tool

### ISSUE THREAD

**Issue by jalal1** [LBNL-UCB-STI/beam#3417]
Hello, 

I am trying to follow the conversation guide for siouxfalls from here: https://beam.readthedocs.io/en/latest/users.html#conversion-instructions

I am facing this error: 
![image](https://user-images.githubusercontent.com/1554493/146095086-3dd6fdaf-2391-48d5-ade0-809668763635.png)

I am still checking the cause, and would appreciate any help if someone faced it before or know the root cause. 

Thank you, 
Jalal

**Comment by dgm90** [comment]
Hey, would you be able to post the log when running the command with `--debug` option, please?

**Comment by jalal1** [comment]
Hello @dgm90, 

The debug file is very big (10 mb). Below is the first error in the top of the file which could be the reason. 

> 2021-12-15T15:36:05.270-0600 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Native file system watching is not available for this operating system.
net.rubygrapefruit.platform.NativeIntegrationLinkageException: Native library 'libnative-platform-file-events.so' could not be loaded for Linux amd64.
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:61)
	at net.rubygrapefruit.platform.file.FileEvents.init(FileEvents.java:35)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:127)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:90)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.lang.UnsatisfiedLinkError: /home/jalalk/.gradle/native/53dbd7edfb1c66fb8903c78663c9afc45aea4f116125fa6feffd364cf09443e8/linux-amd64/libnative-platform-file-events.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/jalalk/.gradle/native/53dbd7edfb1c66fb8903c78663c9afc45aea4f116125fa6feffd364cf09443e8/linux-amd64/libnative-platform-file-events.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:51)
	... 24 more
2021-12-15T15:36:05.303-0600 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: /home/jalalk/.gradle/native
2021-12-15T15:36:05.330-0600 [LIFECYCLE] [org.gradle.launcher.cli.DebugLoggerWarningAction] 

I am not sure if it is safe to share the whole file as indicated in the msg below, but if you think so, and still want it, please let me know so I upload it somewhere or send it by email. 

> #############################################################################
>    WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
> 
>    Debug level logging will leak security sensitive information!
> 
>    https://docs.gradle.org/7.1.1/userguide/logging.html#sec:debug_security
> #############################################################################

Thank you, 
Jalal

**Comment by JustinPihony** [comment]
This sounds like it could be the access for the www-data user as answered [here](https://stackoverflow.com/a/38558668/779513).

**Comment by jalal1** [comment]
Thank you @JustinPihony. I spent some time on this, but still doesn't work. I will check more. 

Thank you again, 
Jalal

**Comment by paulwalter98** [comment]
@jalal1 I am having the same issue. Were you able to resolve the issue?

**Comment by jalal1** [comment]
@paulwalter98 not yet!

**Comment by JustinPihony** [comment]
Can you share your OS information? I'd like to spin up an EC2 instance of that type and see if I can reproduce it

**Comment by jalal1** [comment]
@JustinPihony , unfortunately the machine is no longer alive. In fact, I am not testing beam these days and moved to another direction.

But I think the below are the OS information I got from another opened issue. Thank you.

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
