### ISSUE TITLE
Bug: Race condition in org.matsim.core.scoring.EventsToActivities

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3420]
In one of PILATES runs BEAM died at iteration 4 because of ConcurrentModificationException:

00:57:56.361 [main] ERROR o.m.c.c.MatsimRuntimeModifications - ERROR --- This is an unexpected shutdown!
00:57:56.372 [main] ERROR o.m.c.c.MatsimRuntimeModifications - Shutdown possibly caused by the following Exception:
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at org.matsim.core.scoring.EventsToActivities.finish(EventsToActivities.java:113)
	at org.matsim.core.scoring.EventsToActivities$1.notifyAfterMobsim(EventsToActivities.java:74)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerAfterMobsimEvent(ControlerListenerManagerImpl.java:249)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:216)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:212)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:147)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:28)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy23.run(Unknown Source)
	at beam.sim.BeamHelper.run(BeamHelper.scala:970)
	at beam.sim.BeamHelper.run$(BeamHelper.scala:969)
	at beam.sim.RunBeam$.run(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:682)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:645)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:547)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:530)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:394)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:383)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:10)
	at beam.sim.RunBeam$.main(RunBeam.scala:27)
	at beam.sim.RunBeam.main(RunBeam.scala)

**Comment by JustinPihony** [comment]
This could be fixed via https://github.com/wrashid/matsim/pull/12, but the question is if that is the right solution? Is it ok to be modifying the set  concurrently? Should a lock be used instead - or something to protect in another way?

**Comment by nikolayilyin** [comment]
The original simulation died because of timout. It appears the issue was not in the race condition but in the low instance memory size.
