### ISSUE TITLE
Very big file: beamLog.out

### ISSUE THREAD

**Issue by jalal1** [LBNL-UCB-STI/beam#3434]
Dears, 

I am trying to run a simple simulation with one plan and a new network that I downloaded and cropped using osm and osmosis. 

At this point I set baseDate to UTC without using a gtfs zip file. I am not sure if this related. 
`baseDate = "2016-10-17T00:00:00-00:00" # UTC (Jalal)`
Also tried the dummy gtfs file with the default baseDate value.

When I ran beam, I noticed a very large beamLog.out after about 15 minutes: 
![image](https://user-images.githubusercontent.com/1554493/148692068-27f55551-3e1c-4cd8-b639-8d4b61b919d8.png)

Notice that I ran beamville successfully even though I see the same error i reported in another issue: 

`2022-01-09T11:14:33.561-0600 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Native file system watching is not available for this operating system.
net.rubygrapefruit.platform.NativeIntegrationLinkageException: Native library 'libnative-platform-file-events.so' could not be loaded for Linux amd64.
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:61)
	at net.rubygrapefruit.platform.file.FileEvents.init(FileEvents.java:35)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:127)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:90)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.lang.UnsatisfiedLinkError: /home/jalalk/.gradle/native/53dbd7edfb1c66fb8903c78663c9afc45aea4f116125fa6feffd364cf09443e8/linux-amd64/libnative-platform-file-events.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/jalalk/.gradle/native/53dbd7edfb1c66fb8903c78663c9afc45aea4f116125fa6feffd364cf09443e8/linux-amd64/libnative-platform-file-events.so)`

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings
2022-01-09T11:15:38.076-0600 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
2022-01-09T11:15:38.076-0600 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] **BUILD SUCCESSFUL in 1m 4s**
2022-01-09T11:15:38.076-0600 [LIFECYCLE] [org.gradle.internal.buildevents.TaskExecutionStatisticsReporter] 3 actionable tasks: 1 executed, 2 up-to-date
2022-01-09T11:15:38.076-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Build finished for file system watching' started
2022-01-09T11:15:38.076-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Build finished for file system watching'
2022-01-09T11:15:38.076-0600 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Build finished for file system watching' completed
2022-01-09T11:15:38.127-0600 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-supplier (/home/jalalk/.gradle/caches/7.1.1/md-supplier)
2022-01-09T11:15:38.127-0600 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-supplier (/home/jalalk/.gradle/caches/7.1.1/md-supplier).

**Update: I found the following line keep flushing into the log file: **

`00:02:00.127 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.127 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.127 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.127 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.127 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.127 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.127 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.127 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.127 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.128 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.128 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.128 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.128 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.128 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.128 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.128 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.128 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total population
00:02:00.128 [ClusterSystem-ride-hail-manager-pinned-dispatcher-11] ERROR b.s.ProceduralRideHailFleetInitializer - Can't have more ridehail drivers than total populati`

**Comment by jalal1** [comment]
The error message: "Can't have more ridehail drivers than total population", but it was a little bit confusing because I have one driver in ridehailfleet.csv and one plan in population.xml. Also I explicitly specified the following parameters: 

> beam.agentsim.numAgents = 1
> beam.agentsim.agents.rideHail.numDriversAsFractionOfPopulation=1

 But in beamLog.out it says: 

> ** Found the following deprecated parameters, you can safely remove them from your config file:
> **  
> **  beam.agentsim.agents.rideHail.numDriversAsFractionOfPopulation
> **  beam.agentsim.numAgents

I added one more dummy plan, and it didn't report same error again! 

I see more errors, but I am not sure why: 

Is taz-centers.csv file required? 

`12:28:27.726 [main] ERROR b.a.infrastructure.taz.TAZTreeMap$ - Exception occurred while reading from CSV file from path (using defaultTazTreeMap): java.io.FileNotFoundException: /test/input/beamville/taz-centers.csv
org.matsim.core.utils.io.UncheckedIOException: java.io.FileNotFoundException: /test/input/beamville/taz-centers.csv
	at org.matsim.core.utils.io.IOUtils.getBufferedReader(IOUtils.java:149)
	at org.matsim.core.utils.io.IOUtils.getBufferedReader(IOUtils.java:95)
	at beam.utils.FileUtils$.readerFromFile(FileUtils.scala:186)
	at beam.utils.csv.GenericCsvReader.readAs(GenericCsvReader.scala:21)
	at beam.utils.csv.GenericCsvReader.readAs$(GenericCsvReader.scala:13)
	at beam.utils.csv.GenericCsvReader$.readAs(GenericCsvReader.scala:85)
	at beam.agentsim.infrastructure.taz.CsvTaz$.readCsvFile(CsvTaz.scala:13)
	at beam.agentsim.infrastructure.taz.TAZTreeMap$.fromCsv(TAZTreeMap.scala:141)
	at beam.agentsim.infrastructure.taz.TAZTreeMap$.getTazTreeMap(TAZTreeMap.scala:177)
	at beam.sim.BeamHelper.loadScenario(BeamHelper.scala:291)
	at beam.sim.BeamHelper.loadScenario$(BeamHelper.scala:268)
	at beam.sim.RunBeam$.loadScenario(RunBeam.scala:10)
	at beam.sim.BeamHelper.$anonfun$buildBeamServicesAndScenario$2(BeamHelper.scala:851)
	at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:7)
	at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:20)
	at beam.sim.BeamHelper.buildBeamServicesAndScenario(BeamHelper.scala:767)
	at beam.sim.BeamHelper.buildBeamServicesAndScenario$(BeamHelper.scala:754)
	at beam.sim.RunBeam$.buildBeamServicesAndScenario(RunBeam.scala:10)
	at beam.sim.BeamHelper.prepareBeamService(BeamHelper.scala:583)
	at beam.sim.BeamHelper.prepareBeamService$(BeamHelper.scala:576)
	at beam.sim.RunBeam$.prepareBeamService(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:564)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:554)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:410)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:399)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:10)
	at beam.sim.RunBeam$.main(RunBeam.scala:27)
	at beam.sim.RunBeam.main(RunBeam.scala)
Caused by: java.io.FileNotFoundException: /test/input/beamville/taz-centers.csv`

The error that I think cause the problem is: 

`12:29:09.152 [main] ERROR o.m.c.c.MatsimRuntimeModifications - Getting uncaught Exception in Thread main
java.lang.UnsupportedOperationException: empty.max
	at scala.collection.TraversableOnce.max(TraversableOnce.scala:275)
	at scala.collection.TraversableOnce.max$(TraversableOnce.scala:273)
	at scala.collection.AbstractTraversable.max(Traversable.scala:108)
	at beam.physsim.jdeqsim.EventToHourFrequency.notifyIterationEnds(EventToHourFrequency.scala:47)
	at beam.physsim.jdeqsim.JDEQSimRunner.$anonfun$simulate$12(JDEQSimRunner.scala:150)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
12:29:09.152 [main] ERROR o.m.c.c.MatsimRuntimeModifications - ERROR --- This is an unexpected shutdown!
12:29:09.153 [main] ERROR o.m.c.c.MatsimRuntimeModifications - Shutdown possibly caused by the following Exception:`

I will keep updating this thread if I find the solution. 

Thank you, 
Jalal

**Comment by jalal1** [comment]
@JustinPihony any suggestions about this issue would be appreciated. Thank you for your time. 

Jalal

**Comment by JustinPihony** [comment]
@jalal1 What is the OS that you are using? The lib error seems to be a C++ error (https://stackoverflow.com/questions/36816570/glibcxx-3-4-21-not-defined-in-file-libstdc-so-6-with-link-time-reference). As to the other issues, could you share the config and run command you are using so that we can review it?

**Comment by jalal1** [comment]
Please check below. Thank you. 

[files.zip](https://github.com/LBNL-UCB-STI/beam/files/7954646/files.zip)

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

`./gradlew :run -PappArgs="['--config', 'test/input/bhm/beam.conf']"`
