### ISSUE TITLE
Trouble running test scenario: Cannot read field "transitLayer"

### ISSUE THREAD

**Issue by gregmacfarlane** [LBNL-UCB-STI/beam#3450]
I just checked out the BEAM develop branch on a new computer (Mac M1), and I am getting an error running both the beamville and the sl-light scenarios. I'm using the test scenarios without modification,

```sh
--config test/input/sf-light/sf-light-0.5k.conf
```

The error is 

```sh
12:09:05.372 INFO  b.r.r5.DefaultNetworkCoordinator - Initializing router by reading network from: /Users/gregmacfarlane/projects/beam/test/input/sf-light/r5/network.dat
Exception in thread "main" java.lang.NullPointerException: Cannot read field "transitLayer" because the return value of "beam.router.r5.NetworkCoordinator.transportNetwork()" is null
	at beam.router.r5.NetworkCoordinator.convertFrequenciesToTrips(NetworkCoordinator.scala:163)
	at beam.router.r5.NetworkCoordinator.convertFrequenciesToTrips$(NetworkCoordinator.scala:162)
	at beam.router.r5.DefaultNetworkCoordinator.convertFrequenciesToTrips(DefaultNetworkCoordinator.scala:8)
	at beam.router.r5.DefaultNetworkCoordinator.postProcessing(DefaultNetworkCoordinator.scala:16)
	at beam.router.r5.NetworkCoordinator.init(NetworkCoordinator.scala:69)
	at beam.router.r5.NetworkCoordinator.init$(NetworkCoordinator.scala:66)
	at beam.router.r5.DefaultNetworkCoordinator.init(DefaultNetworkCoordinator.scala:8)
	at beam.sim.BeamHelper.buildNetworkCoordinator(BeamHelper.scala:988)
	at beam.sim.BeamHelper.buildNetworkCoordinator$(BeamHelper.scala:982)
	at beam.sim.RunBeam$.buildNetworkCoordinator(RunBeam.scala:10)
	at beam.sim.BeamHelper.loadScenario(BeamHelper.scala:289)
	at beam.sim.BeamHelper.loadScenario$(BeamHelper.scala:269)
	at beam.sim.RunBeam$.loadScenario(RunBeam.scala:10)
	at beam.sim.BeamHelper.$anonfun$buildBeamServicesAndScenario$2(BeamHelper.scala:890)
	at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:7)
	at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:20)
	at beam.sim.BeamHelper.buildBeamServicesAndScenario(BeamHelper.scala:806)
	at beam.sim.BeamHelper.buildBeamServicesAndScenario$(BeamHelper.scala:794)
	at beam.sim.RunBeam$.buildBeamServicesAndScenario(RunBeam.scala:10)
	at beam.sim.BeamHelper.prepareBeamService(BeamHelper.scala:604)
	at beam.sim.BeamHelper.prepareBeamService$(BeamHelper.scala:597)
	at beam.sim.RunBeam$.prepareBeamService(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:585)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:575)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:431)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:420)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:10)
	at beam.sim.RunBeam$.main(RunBeam.scala:27)
	at beam.sim.RunBeam.main(RunBeam.scala)
```

Now, I have confirmed that the `network.dat` file is not present in the input folder locally or in the repository, but I believe that this is an intermediate file that is somehow not getting converted.

Output log: 
[beamLog.log](https://github.com/LBNL-UCB-STI/beam/files/7907929/beamLog.log)

More system information:
  - Java 16
  - Mac OS 15, with amd64 architecture
  - Running through IntelliJ

**Comment by zneedell** [comment]
This is definitely an area where people have run into problems before. Could you check that all of these files are deleted from the r5 directory before you run?

> network.dat
> osm.mapdb
> osm.mapdb.p
> physsim-network.xml

Another thing that has tripped people up in the past is the network .pbf file not being correctly synced from git, so think you could check to see if it's not empty?

I also asked around whether anyone has successfully run BEAM on a M1, so I'll let you know about that

**Comment by gregmacfarlane** [comment]
I've confirmed that the `sflight_muni.osm.pbf` is not empty (12.5 MB), and that those files are deleted from the inputs folder prior to running. Deleting the files caused a different error,

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.conveyal.r5.streets.StreetLayer.findSplit(StreetLayer.java:1315)
	at com.conveyal.r5.streets.StreetLayer.getOrCreateVertexNear(StreetLayer.java:1136)
	at com.conveyal.r5.streets.StreetLayer.createAndLinkVertex(StreetLayer.java:1278)
	at com.conveyal.r5.streets.StreetLayer.associateStops(StreetLayer.java:1330)
	at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:238)
	at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:178)
	at com.conveyal.r5.transit.TransportNetwork.fromDirectory(TransportNetwork.java:306)
	at beam.router.r5.NetworkCoordinator.$anonfun$loadNetwork$4(NetworkCoordinator.scala:103)
	at beam.router.r5.NetworkCoordinator.$anonfun$loadNetwork$4$adapted(NetworkCoordinator.scala:96)
	at beam.utils.FileUtils$.$anonfun$readOrCreateFile$4(FileUtils.scala:149)
	at scala.util.Try$.apply(Try.scala:213)
	at beam.utils.FileUtils$.readOrCreateFile(FileUtils.scala:149)
	at beam.router.r5.NetworkCoordinator.loadNetwork(NetworkCoordinator.scala:96)
	at beam.router.r5.NetworkCoordinator.loadNetwork$(NetworkCoordinator.scala:74)
	at beam.router.r5.DefaultNetworkCoordinator.loadNetwork(DefaultNetworkCoordinator.scala:8)
	at beam.router.r5.NetworkCoordinator.init(NetworkCoordinator.scala:68)
	at beam.router.r5.NetworkCoordinator.init$(NetworkCoordinator.scala:66)
	at beam.router.r5.DefaultNetworkCoordinator.init(DefaultNetworkCoordinator.scala:8)
	at beam.sim.BeamHelper.buildNetworkCoordinator(BeamHelper.scala:988)
	at beam.sim.BeamHelper.buildNetworkCoordinator$(BeamHelper.scala:982)
	at beam.sim.RunBeam$.buildNetworkCoordinator(RunBeam.scala:10)
	at beam.sim.BeamHelper.loadScenario(BeamHelper.scala:289)
	at beam.sim.BeamHelper.loadScenario$(BeamHelper.scala:269)
	at beam.sim.RunBeam$.loadScenario(RunBeam.scala:10)
	at beam.sim.BeamHelper.$anonfun$buildBeamServicesAndScenario$2(BeamHelper.scala:890)
	at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:7)
	at beam.utils.ProfilingUtils$.timed(ProfilingUtils.scala:20)
	at beam.sim.BeamHelper.buildBeamServicesAndScenario(BeamHelper.scala:806)
	at beam.sim.BeamHelper.buildBeamServicesAndScenario$(BeamHelper.scala:794)
	at beam.sim.RunBeam$.buildBeamServicesAndScenario(RunBeam.scala:10)
	at beam.sim.BeamHelper.prepareBeamService(BeamHelper.scala:604)
	at beam.sim.BeamHelper.prepareBeamService$(BeamHelper.scala:597)
	at beam.sim.RunBeam$.prepareBeamService(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:585)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:575)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:431)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:420)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:10)
	at beam.sim.RunBeam$.main(RunBeam.scala:27)
	at beam.sim.RunBeam.main(RunBeam.scala)
Caused by: java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
	at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
	at java.desktop/javax.imageio.spi.ServiceRegistry.<init>(ServiceRegistry.java:117)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:155)
	at org.geotools.factory.FactoryRegistry.<init>(FactoryRegistry.java:146)
	at org.geotools.factory.FactoryCreator.<init>(FactoryCreator.java:82)
	at org.geotools.referencing.ReferencingFactoryFinder.getServiceRegistry(ReferencingFactoryFinder.java:115)
	at org.geotools.referencing.ReferencingFactoryFinder.getFactory(ReferencingFactoryFinder.java:197)
	at org.geotools.referencing.ReferencingFactoryFinder.getCoordinateOperationFactory(ReferencingFactoryFinder.java:322)
	at org.geotools.geometry.TransformedDirectPosition.<init>(TransformedDirectPosition.java:169)
	at org.geotools.referencing.GeodeticCalculator.<init>(GeodeticCalculator.java:221)
	at org.geotools.referencing.GeodeticCalculator.<init>(GeodeticCalculator.java:197)
	at com.conveyal.r5.streets.Split.<clinit>(Split.java:71)
	... 41 more
Caused by: java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class

```

I expect that I initially got this error, and then the original error when I tried to re-run. Complete log:
[beamLog.log](https://github.com/LBNL-UCB-STI/beam/files/7916337/beamLog.log)

**Comment by zneedell** [comment]
Hmm, thanks. Definitely smells like it could be an architecture issue. @dgm90 is going to try running it on an M1 and we'll let you know how it goes.

**Comment by dgm90** [comment]
Hey, a quick googling of the last error `Caused by: java.lang.IllegalArgumentException: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class` tells me that this class should be run on Java 8 and not higher :(
In beam `org.geotools.gt-opengis` of 16.0 version is used and here is the readme for it https://github.com/geotools/geotools/blob/16.0/README.html#L67
So please try to use [java8](https://www.azul.com/downloads/?version=java-8-lts&os=macos&architecture=arm-64-bit&package=jdk) 


Afterwards I think you might run into an issue, that `com.uber.h3` library doesn't support the arm architecture. They are working on it, please [see here](https://github.com/uber/h3-java/pull/89). You can try to use the jar provided in the issue.

I've set everything up to use this jar locally and ran the above scenario successfully.

**Comment by gregmacfarlane** [comment]
Okay, switching to Java8 gives me the error that @dgm90 expects,
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: No native resource found at /darwin-arm64/libh3-java.dylib
	at com.uber.h3core.H3CoreLoader.copyResource(H3CoreLoader.java:68)
	at com.uber.h3core.H3CoreLoader.loadNatives(H3CoreLoader.java:120)
	at com.uber.h3core.H3CoreLoader.loadNatives(H3CoreLoader.java:89)
	at com.uber.h3core.H3Core.newInstance(H3Core.java:75)
	at beam.agentsim.infrastructure.taz.H3TAZ$.<init>(H3TAZ.scala:81)
	at beam.agentsim.infrastructure.taz.H3TAZ$.<clinit>(H3TAZ.scala)
	at beam.agentsim.infrastructure.taz.H3TAZ.<init>(H3TAZ.scala:28)
	at beam.sim.BeamHelper.loadScenario(BeamHelper.scala:334)
```

To fix this, I downloaded the new H3 snapshot jar and stored it at `libs/`. Then I made the following two changes to build.gradle:

```
@@ -115,6 +115,9 @@ allprojects {
             allowInsecureProtocol = true
         }
         maven { url "https://jitpack.io" }
+        flatDir{
+            dirs 'libs'
+        }
     }
 }
@@ -207,7 +210,7 @@ dependencies {
     implementation group: 'com.graphhopper', name: 'graphhopper-core', version: '2.3'
     implementation "com.sigopt:sigopt-java:4.9.0"

-    implementation("com.uber:h3:3.4.1")
+    implementation("com.uber:h3:3.7.2-SNAPSHOT")
     implementation("com.github.LBNL-UCB-STI:jsprit-wrapper:v0.5.1")

     testImplementation group: 'junit', name: 'junit', version: '4.8'
```

This runs successfully. I don't think you want this to be PR'd, but updating h3 should be a priority once that new version is released.

**Comment by g-derzhavets** [comment]
@gregmacfarlane we just merged the `h3.uber` bumped to `v3.7.2`, that supports M1. Fyi
