### ISSUE TITLE
BEAM ignoring input config directory

### ISSUE THREAD

**Issue by paulwalter98** [LBNL-UCB-STI/beam#3478]
When trying to run simulations using my own data, I am running into an issue where running BEAM results in it looking in the incorrect location for input files. Specifically, BEAM throws the following error when running any non-test scenario:
```
Exception in thread "main" org.matsim.core.utils.io.UncheckedIOException: java.io.FileNotFoundException: /test/input/beamville/vehicleTypes.csv
        at org.matsim.core.utils.io.IOUtils.getBufferedReader(IOUtils.java:149)
        at org.matsim.core.utils.io.IOUtils.getBufferedReader(IOUtils.java:95)
        at beam.utils.FileUtils$.readerFromFile(FileUtils.scala:186)
        at beam.utils.BeamVehicleUtils$.readCsvFileByLine(BeamVehicleUtils.scala:149)
        at beam.utils.BeamVehicleUtils$.readBeamVehicleTypeFile(BeamVehicleUtils.scala:63)
        at beam.utils.InputConsistencyCheck$.checkConsistency(InputConsistencyCheck.scala:46)
        at beam.sim.BeamHelper.setupBeamWithConfig(BeamHelper.scala:954)
        at beam.sim.BeamHelper.setupBeamWithConfig$(BeamHelper.scala:941)
        at beam.sim.RunBeam$.setupBeamWithConfig(RunBeam.scala:10)
        at beam.sim.BeamHelper.prepareBeamService(BeamHelper.scala:601)
        at beam.sim.BeamHelper.prepareBeamService$(BeamHelper.scala:597)
        at beam.sim.RunBeam$.prepareBeamService(RunBeam.scala:10)
        at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:585)
        at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:575)
        at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:10)
        at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:431)
        at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:420)
        at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:10)
        at beam.sim.RunBeam$.main(RunBeam.scala:27)
        at beam.sim.RunBeam.main(RunBeam.scala)
Caused by: java.io.FileNotFoundException: /test/input/beamville/vehicleTypes.csv
        ... 20 more
```

To run BEAM, I am using the following command from the beam directory on my PC:

`gradlew :run -PappArgs="['--config', 'production/raleigh/ral.conf']"`

I am not sure why BEAM is looking for the vehicleTypes.csv in test/input/beamville when that is not the directory I am passing to BEAM.

My production/raleigh directory has all the necessary input files and ral.conf was written based on beam.conf (some items, like ride hail, have been removed). The ral.conf file is shown below:

```
include "../common/akka.conf"
include "../common/metrics.conf"
include "../common/matsim.conf"

##################################################################
# Agentsim
##################################################################
beam.agentsim.simulationName = "raleigh"
beam.agentsim.agentSampleSizeAsFractionOfPopulation = 1.0
beam.agentsim.firstIteration = 0
beam.agentsim.lastIteration = 2
beam.agentsim.thresholdForWalkingInMeters = 100
beam.agentsim.thresholdForMakingParkingChoiceInMeters = 200
beam.agentsim.schedulerParallelismWindow = 30
beam.agentsim.timeBinSize = 3600
beam.agentsim.startTime = "00:00:00"
beam.agentsim.endTime = "30:00:00"

# MODE CHOICE OPTIONS:
# ModeChoiceMultinomialLogit ModeChoiceTransitIfAvailable ModeChoiceDriveIfAvailable ModeChoiceRideHailIfAvailable
# ModeChoiceUniformRandom ModeChoiceLCCM
beam.agentsim.agents.modalBehaviors.modeChoiceClass = "ModeChoiceMultinomialLogit"
beam.agentsim.agents.modalBehaviors.defaultValueOfTime = 7.25
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.transfer = 0.0
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.car_intercept = 2.0
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.walk_transit_intercept = 0.0
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.drive_transit_intercept = 2.0
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.ride_hail_transit_intercept = 0.0
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.ride_hail_intercept = 10.0
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.ride_hail_pooled_intercept = 10.0
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.walk_intercept = 0.0
beam.agentsim.agents.modalBehaviors.mulitnomialLogit.params.bike_intercept = 0.0
beam.agentsim.agents.modalBehaviors.overrideAutomationLevel = 5
beam.agentsim.agents.modalBehaviors.overrideAutomationForVOTT = false
beam.agentsim.agents.modalBehaviors.lccm.filePath = ${beam.inputDirectory}"/lccm-long.csv"


beam.agentsim.agents.plans {
  inputPlansFilePath = ${beam.inputDirectory}"/population.xml"
  inputPersonAttributesFilePath = ${beam.inputDirectory}"/populationAttributes.xml"
}
beam.agentsim.agents.households {
  inputFilePath = ${beam.inputDirectory}"/households.xml"
  inputHouseholdAttributesFilePath = ${beam.inputDirectory}"/householdAttributes.xml"
}

#BeamVehicles Params
beam.agentsim.agents.vehicles.beamFuelTypesFile = ${beam.inputDirectory}"/beamFuelTypes.csv"
beam.agentsim.agents.vehicles.beamVehicleTypesFile = ${beam.inputDirectory}"/vehicleTypes.csv"
beam.agentsim.agents.vehicles.beamVehiclesFile = ${beam.inputDirectory}"/vehicles.csv"
beam.agentsim.agents.vehicles.sharedFleets = []

# Population Adjustment (DEFAULT_ADJUSTMENT | PERCENTAGE_ADJUSTMENT)
beam.agentsim.populationAdjustment="DEFAULT_ADJUSTMENT"

#TAZ params
beam.agentsim.taz.filePath=${beam.inputDirectory}"/taz-centers.csv"
beam.agentsim.taz.parkingFilePath = ${beam.inputDirectory}"/taz-parking.csv"
# Scaling and Tuning Params
beam.agentsim.tuning.transitCapacity = 0.1
beam.agentsim.tuning.transitPrice = 1.0
beam.agentsim.tuning.tollPrice = 1.0
beam.agentsim.tuning.rideHailPrice = 1.0
###########################
# Physsim
###########################
beam.physsim.inputNetworkFilePath = ${beam.routing.r5.directory}"/network.xml"
beam.physsim.flowCapacityFactor = 0.0001
beam.physsim.storageCapacityFactor = 1.0
beam.physsim.writeMATSimNetwork = false
beam.physsim.ptSampleSize = 1.0
beam.physsim.jdeqsim.agentSimPhysSimInterfaceDebugger.enabled = false
beam.physsim.skipPhysSim = false
beam.physsim.jdeqsim.cacc.enabled = false
beam.physsim.jdeqsim.cacc.minRoadCapacity = 1999
beam.physsim.jdeqsim.cacc.minSpeedMetersPerSec = 7
beam.physsim.jdeqsim.cacc.speedAdjustmentFactor = 1.0

beam.router.skim = {
  h3Resolution = 6
  keepKLatestSkims = 1
  writeSkimsInterval = 1
  writeAggregatedSkimsInterval = 1
  collectFullCarSkimsInterval = 1
  travel-time-skimmer {
    name = "travel-time-skimmer"
    fileBaseName = "skimsTravelTimeObservedVsSimulated"
  }
  origin_destination_skimmer {
    name = "od-skimmer"
    fileBaseName = "skimsOD"
    writeAllModeSkimsForPeakNonPeakPeriodsInterval = 0
    writeFullSkimsInterval = 0
  }
  taz-skimmer {
    name = "taz-skimmer"
    fileBaseName = "skimsTAZ"
  }
}
#helics
beam.cosim.helics = {
  timeStep = "300"
  federateName = "BeamFederate"
}

###########################
# Replanning
###########################
beam.replanning {
  maxAgentPlanMemorySize = 4
  Module_1 = "SelectExpBeta"
  ModuleProbability_1 = 0.7
  Module_2 = "ClearRoutes"
  ModuleProbability_2 = 0.1
  Module_3 = "ClearModes"
  ModuleProbability_3 = 0.1
  Module_4 = "TimeMutator"
  ModuleProbability_4 = 0.1
  fractionOfIterationsToDisableInnovation = 9999999
  cleanNonCarModesInIteration = 1
}

##################################################################
# OUTPUTS
##################################################################
# The outputDirectory is the base directory where outputs will be written. The beam.agentsim.simulationName param will
# be used as the name of a sub-directory beneath the baseOutputDirectory for simulation results.
# If addTimestampToOutputDirectory == true, a timestamp will be added, e.g. "raleigh_2017-12-18_16-48-57"
beam.outputs.baseOutputDirectory = "output/raltest"
beam.outputs.baseOutputDirectory = ${?BEAM_OUTPUT}
beam.outputs.addTimestampToOutputDirectory = true

# To keep all logging params in one place, BEAM overrides MATSim params normally in the controller config module
beam.outputs.defaultWriteInterval = 1
beam.outputs.writePlansInterval = ${beam.outputs.defaultWriteInterval}
beam.outputs.writeEventsInterval = ${beam.outputs.defaultWriteInterval}
beam.physsim.writeEventsInterval = ${beam.outputs.defaultWriteInterval}
beam.physsim.writePlansInterval = ${beam.outputs.defaultWriteInterval}
beam.outputs.writeAnalysis = false
beam.outputs.writeLinkTraversalInterval = 0
beam.physsim.linkStatsWriteInterval = 0

# The remaining params customize how events are written to output files
beam.outputs.events.fileOutputFormats = "csv,xml" # valid options: xml(.gz) , csv(.gz), none - DEFAULT: csv.gz

# Events Writing Logging Levels:
beam.outputs.events.eventsToWrite = "PersonDepartureEvent,PersonArrivalEvent,ActivityEndEvent,ActivityStartEvent,PersonEntersVehicleEvent,PersonLeavesVehicleEvent,ModeChoiceEvent,PathTraversalEvent,ReserveRideHailEvent,ReplanningEvent,RefuelSessionEvent,TeleportationEvent,ChargingPlugInEvent,ChargingPlugOutEvent,ParkingEvent,LeavingParkingEvent"
beam.outputs.stats.binSize = 3600

##################################################################
# Debugging
##################################################################
beam.debug.debugEnabled = true
beam.debug.debugActorTimerIntervalInSec = 10
beam.debug.actor.logDepth = 12

beam.debug.stuckAgentDetection {
  checkIntervalMs = 200
  checkMaxNumberOfMessagesEnabled = true
  defaultTimeoutMs = 60000
  enabled = true
  overallSimulationTimeoutMs = 100000
  thresholds = [
    {
      actorTypeToMaxNumberOfMessages {
        population = 1
        rideHailAgent = 1
        transitDriverAgent = 1
      }
      markAsStuckAfterMs = 20000
      triggerType = "beam.agentsim.agents.InitializeTrigger"
    },
    {
      actorTypeToMaxNumberOfMessages {
        population = 11
      }
      markAsStuckAfterMs = 20000
      triggerType = "beam.agentsim.agents.PersonAgent$ActivityEndTrigger"
    },
    {
      actorTypeToMaxNumberOfMessages {
        population = 1
      }
      markAsStuckAfterMs = 20000
      triggerType = "beam.agentsim.agents.PersonAgent$ActivityStartTrigger"
    },
    {
      actorTypeToMaxNumberOfMessages {
        population = 60
      }
      markAsStuckAfterMs = 20000
      triggerType = "beam.agentsim.agents.PersonAgent$PersonDepartureTrigger"
    },
    {
      actorTypeToMaxNumberOfMessages {
        population = 20
      }
      markAsStuckAfterMs = 20000
      triggerType = "beam.agentsim.agents.modalbehaviors.DrivesVehicle$AlightVehicleTrigger"
    },
    {
      actorTypeToMaxNumberOfMessages {
        population = 20
      }
      markAsStuckAfterMs = 20000
      triggerType = "beam.agentsim.agents.modalbehaviors.DrivesVehicle$BoardVehicleTrigger"
    },
    {
      actorTypeToMaxNumberOfMessages {
        population = 80
        rideHailAgent = 400
        transitDriverAgent = 114
      }
      markAsStuckAfterMs = 20000
      triggerType = "beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger"
    },
    {
      actorTypeToMaxNumberOfMessages {
        population = 80
        rideHailAgent = 400
        transitDriverAgent = 114
      }
      markAsStuckAfterMs = 20000
      triggerType = "beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger"
    },
    {
      actorTypeToMaxNumberOfMessages {
        transitDriverAgent = 1
      }
      markAsStuckAfterMs = 20000
      triggerType = "beam.agentsim.scheduler.BeamAgentScheduler$KillTrigger"

    }
  ]
}
##################################################################
# SPATIAL
##################################################################
beam.spatial = {
  localCRS = "epsg:32631"  # what crs to use for distance calculations, must be in units of meters
  boundingBoxBuffer = 10000 # meters of buffer around network for defining extend of spatial indices
}

##################################################################
# BEAM ROUTING SERVICE
##################################################################
beam.routing {
  #Base local date in ISO 8061 YYYY-MM-DDTHH:MM:SS+HH:MM
  baseDate = "2021-02-15T00:00:00-05:00"
  transitOnStreetNetwork = true # PathTraversalEvents for transit vehicles
  r5 {
    directory = ${beam.inputDirectory}"/r5"
    # Departure window in min
    departureWindow = 1.0167
    osmFile = ${beam.inputDirectory}"/r5/filtered.osm.pbf"
    osmMapdbFile = ${beam.inputDirectory}"/r5/osm.mapdb"
    mNetBuilder.fromCRS = "epsg:4326" # WGS84
    mNetBuilder.toCRS = ${beam.spatial.localCRS}
  }
  startingIterationForTravelTimesMSA = 1
  gh.useAlternativeRoutes = false
}
##################################################################
# Calibration
##################################################################
beam.calibration.objectiveFunction = "ModeChoiceObjectiveFunction"
beam.calibration.mode.benchmarkFilePath=${beam.inputDirectory}"/calibration/benchmark.csv"
beam.calibration.counts {
  countsScaleFactor = 10.355
  writeCountsInterval = 0
  averageCountsOverIterations = ${beam.outputs.defaultWriteInterval}
}

```
I am running BEAM 0.7.0 with Java Version 1.8.0_311 and Gradle 7.3.3,  on a Windows 10 device. This is not happening when running either the beamville or sf-light scenarios.

**Comment by JustinPihony** [comment]
Hi @paulwalter98 - this comes from `beam.agentsim.agents.vehicles.vehicleTypesFilePath`, where your setting is `beam.agentsim.agents.vehicles.beamVehicleTypesFile`. This was changed [here](https://github.com/LBNL-UCB-STI/beam/pull/1355), but not in the documentation. I have created https://github.com/LBNL-UCB-STI/beam/pull/3491 to resolve that.
