### ISSUE TITLE
Failed to run production/sfbay/base.conf

### ISSUE THREAD

**Issue by zihaooo** [LBNL-UCB-STI/beam#3768]
I have installed beam and ran the `test/input/beamville/beam.conf` and `test/input/sf-light/sf-light.conf` successfully.

However, when I tried to run `production/sfbay/base.conf`, the following error occurred instantly:

> 21:54:07.269 [main] ERROR beam.sim.RunBeam$ - Exception occurred:
java.lang.IllegalArgumentException: It is expected that beam.physsim.inputNetworkFilePath points to the file inside beam.routing.r5.directory [./beam/production/sfbay/r5-simple-no-local]. Instead it points to: [./beam/production/sfbay/r5-no-local/physsim-network.xml]
	at beam.utils.ConfigConsistencyComparator$.checkMapFilesDirectoriesConsistency(ConfigConsistencyComparator.scala:197)
	at beam.utils.ConfigConsistencyComparator$.parseBeamTemplateConfFile(ConfigConsistencyComparator.scala:47)
	at beam.sim.BeamHelper.prepareConfig(BeamHelper.scala:471)
	at beam.sim.BeamHelper.prepareConfig$(BeamHelper.scala:457)
	at beam.sim.RunBeam$.prepareConfig(RunBeam.scala:10)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:446)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:441)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:10)
	at beam.sim.RunBeam$.main(RunBeam.scala:30)
	at beam.sim.RunBeam.main(RunBeam.scala)

If I change the line 63 from
```
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5-no-local/physsim-network.xml"
```
to 
```
beam.physsim.inputNetworkFilePath = ${beam.inputDirectory}"/r5-simple-no-local/physsim-network.xml"
```
I can run without this error, but another occurred.

The start command is
```bash
export MAXRAM=200g; ./gradlew :run -PappArgs="['--config', 'production/sfbay/base.conf']"
```
The program can run for a while, but finally, the following error occurred:

> > Configure project :
> [-Xmx200g, -Xms100g, -XX:+UseParallelGC, -XX:+UseParallelOldGC, -XX:MetaspaceSize=150M, -Djava.awt.headless=true, -Dlogback.configurationFile=logback_prod.xml, -Xss2048k, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -Xloggc:gc_08-25-2023_21-04-53.log, -Dcom.sun.management.jmxremote, -Dcom.sun.management.jmxremote.port=9005, -Dcom.sun.management.jmxremote.rmi.port=9005, -Dcom.sun.management.jmxremote.host=127.0.0.1, -Dcom.sun.management.jmxremote.local.only=true, -Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.ssl=false, -Djava.net.preferIPv4Stack=true, -Djava.rmi.server.hostname=127.0.0.1]
> 
> > Task :run
> 
>   ________
>   ___  __ )__________ _______ ___
>   __  __  |  _ \  __ `/_  __ `__ \
>   _  /_/ //  __/ /_/ /_  / / / / /
>   /_____/ \___/\__,_/ /_/ /_/ /_/
> 
>  _____________________________________
> 
>     
> Received 2 arguments: List(--config, production/sfbay/base.conf)
> Java version: 1.8.0_371
> JVM args: List(-Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.host=127.0.0.1, -Dcom.sun.management.jmxremote.local.only=true, -Dcom.sun.management.jmxremote.port=9005, -Dcom.sun.management.jmxremote.rmi.port=9005, -Dcom.sun.management.jmxremote.ssl=false, -Djava.awt.headless=true, -Djava.net.preferIPv4Stack=true, -Djava.rmi.server.hostname=127.0.0.1, -Dlogback.configurationFile=logback_prod.xml, -XX:+UseParallelGC, -XX:+UseParallelOldGC, -XX:MetaspaceSize=150M, -Xss2048k, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -Xloggc:gc_08-25-2023_21-04-53.log, -Xms100g, -Xmx200g, -Dcom.sun.management.jmxremote, -Dfile.encoding=UTF-8, -Duser.country, -Duser.language=en, -Duser.variant)
> Heap size: 95.8 GB
> Heap max memory: 177.8 GB
> Heap free memory: 90.8 GB
> Exception occurred: java.lang.NullPointerException
> 
> > Task :run FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':run'.
> > Process 'command '/opt/java/jdk1.8.0_371/bin/java'' finished with non-zero exit value 2
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 10m 3s
> 3 actionable tasks: 1 executed, 2 up-to-date

Can someone tell me what I am doing wrong?

Here is some information necessary:
OS:  Ubuntu 22.04
Java: 1.8.0_371
`beam` branch/commit: develop/7e8d1f33f35c41a1ff788220320703ab875dbcb4
`beam-data-sfbay` branch/commit: develop/5fcac035282b941643a7e6e7c07cb503c52914ec

**Comment by nikolayilyin** [comment]
Could you, please, provide the beam log file from the simulation that was running for some time.
The path to the log file:
output / city name  / simulation name__date time / beamLog.out

**Comment by zihaooo** [comment]
Thanks for your reply. The beamLog.out is empty. I don't know if it is because of my launch method. I launched the simulation with the following command:

``` bash
export MAXRAM=200g; ./gradlew :run -PappArgs="['--config', 'production/sfbay/base.conf']"
```

**Comment by dimaopen** [comment]
Try using 
```bash
export MAXRAM=200g; ./gradlew :run -PappArgs="['--config', 'production/sfbay/sfbay-base.conf']"
```
Please validate that the conf file exists. You need to get the sfbay data before as described in the [documentation](https://beam-lbnl.readthedocs.io/en/latest/developers.html#production-data-and-git-submodules).
