### ISSUE TITLE
Continue simulation if beam.calibration.mode.benchmarkFileLoc is not found

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#774]
Currently `ModeChosenStats` stops the whole simualtion with uncaught exception:

```
15:22:24.009 ERROR o.m.c.c.MatsimRuntimeModifications - Getting uncaught Exception in Thread main
java.io.FileNotFoundException:  (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at beam.analysis.plots.ModeChosenStats.benchmarkCsvLoader(ModeChosenStats.java:443)
        at beam.analysis.plots.ModeChosenStats.createGraph(ModeChosenStats.java:112)
        at beam.analysis.plots.GraphsStatsAgentSimEventsListener.createGraphs(GraphsStatsAgentSimEventsListener.java:134)
        at beam.sim.BeamSim.$anonfun$notifyIterationEnds$1(BeamSim.scala:157)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by REASY** [comment]
Closed by https://github.com/LBNL-UCB-STI/beam/pull/776
